scripts/deploy.sh, scripts/deploy_webhook.py
Since MyPy cannot understand dynamically generated `__all__` in `--strict` mode, this will ensure users can still use `mypy --strict` with their applications without us hardcoding around 100 names into each package-level `__init__` module.
=> Updated deploy script to re-generate mypy stubs for --strict support.

hikari/impl/bot.py
This should reduce exception spam caused by invoking `await bot.close()` from a listener.
The application itself may still be raising other errors if you use a Windows proactor event loop, from what I have seen in other user's logs, but alas I cannot reproduce this currently.
=> Amended 'BotApp.run' to not reraise exceptions caused by graceful shutdown.

.run/Unit Tests.run.xml, hikari/impl/special_endpoints.py, pipelines/format.nox.py
* fix remove_trailing_whitespaces_for_file using inconsistent newlines between oses
* rename the unit tests run.xml task to pytest
Increase page size for fetch members plus task fix and rename.
=> Increase page size for fetch members plus task fix and rename.

hikari/api/cache.py, hikari/api/event_dispatcher.py, hikari/api/rest.py, hikari/api/shard.py, hikari/config.py, hikari/events/base_events.py, hikari/events/channel_events.py, hikari/events/guild_events.py, hikari/impl/bot.py, hikari/impl/buckets.py, hikari/impl/rate_limits.py, hikari/impl/rest.py, hikari/impl/shard.py, hikari/models/applications.py, hikari/models/channels.py, hikari/models/embeds.py, hikari/models/guilds.py, hikari/models/invites.py, hikari/models/users.py, hikari/models/webhooks.py, hikari/traits.py, hikari/utilities/attr_extensions.py, hikari/utilities/data_binding.py, hikari/utilities/files.py, hikari/utilities/iterators.py, scripts/deploy.sh
Remove `or None` from documentation. Fixes wrong linking in documentation
None
=> Remove `or None` from documentation

hikari/impl/shard.py, tests/hikari/impl/test_shard.py
Discord appears to be sending 520 HTTP status codes from the gateway at certain times, with no info indicating what it is.
Appears to be something Cloudflare can spit out if Discord fails to communicate a response to them correctly, apparently.
Assuming this is just a regression or something on their side, so I have added a handler that can log this correctly.
=> Handling aiohttp.WSServerUpgradeError

hikari/impl/bot.py
`BotApp(intents=None)` will now issue a deprecated warning to logs on application initialization, ahead of the planned deprecation in October 2020.
=> Add deprecation warning to use of intents.

hikari/impl/shard.py, tests/hikari/impl/test_shard.py
Added a missing test case that inspects how the aiohttp ClientSession gets initialized.
The client session should now force the closure of the single connection connector pool once done with, which hopefully should reduce lingering connections that may affect shutdown times.
=> Gateway websocket closure forcing, and new missing test cases.

hikari/impl/bot.py
State will now default to being __enabled__ on all applications unless explicitly turned off.
=> Defaulted state to being enabled by default on BotApp.

hikari/impl/shard.py
Fix naming issue in shard ratelimiter
None
=> Fix naming issue in shard ratelimiter

hikari/guilds.py, hikari/impl/entity_factory.py, hikari/invites.py, hikari/utilities/cache.py, hikari/utilities/constants.py, tests/hikari/impl/test_entity_factory.py, tests/hikari/impl/test_stateful_cache.py
* Removed dead max presences and members values from gateway guild.
* Fixed consistency for approx active member field naming between models.
* Narrow the scope of "with_count" only rest guild attributes to make them always required
- [x ] I have made unittests according to the code I have added/modified/deleted.
=> Remove, narrow and fixup some guild related fields

tests/hikari/hikari_test_helpers.py
Remove "fqn" helper methods and make "stupid_windows_please_stop_breaking_my_tests" less system specific
- [x ] I have made unittests according to the code I have added/modified/deleted.
=> Remove "fqn" helper methods plus some generalisation

.travis.yml, MANIFEST.in, README.md, hikari/utilities/date.py, pipelines/pytest.nox.py, requirements.txt, setup.py, speedup-requirements.txt
Without this, defaults are to use pure-Python implementations of stuff
where possible.
This fixes an issue where people without Visual C++ Redist 14.0 could not
install Hikari v2.0.0.dev74.
Fixes #116.
=> Added optional `pip install hikari[speedups]` to get compiled modules.

.travis.yml, hikari/impl/rate_limits.py, tests/hikari/impl/test_rate_limits.py
* ensure guild_chunker.close is awaited.
* Fix accidental call to pytest.skip instead of pytest.mark.skip in test_mapping.py.
=> Ensure ExponentialBackOff respects float limitations.

.travis.yml, scripts/test_twemoji_mapping.py
This will allow the job to run every time the a pr is made to verify (permission granted by the owner of the mapping)
=> Re-add normal twemoji session

hikari/impl/shard.py
This caused exceptions to be discarded if the websocket had already cloesd, causing an infinite restart loop as the gateway shard would assume the connection closed without a reason when passing invalid intents, for example.
=> Fixed a logic error in websocket init logic

hikari/impl/stateful_event_manager.py, tests/hikari/hikari_test_helpers.py
shard.request_guild_members in places to avoid it blocking other stuff unnecessarily.
=> avoid the shard ratelimits delaying event dispatch

hikari/impl/rest.py, hikari/impl/shard.py, tests/hikari/impl/test_rest.py
This will allow users to post debug logs in issues safely without leaking
credentials by accident, especially where logs are very long and may
result in tokens being missed.
New REST format:
```
User-Agent: DiscordBot (https://github.com/nekokatt/hikari, 2.0.0) Nekokatt AIOHTTP/3.6.2 CPython/3.8.5 Linux 64bit
X-RateLimit-Precision: millisecond
Authorization: **REDACTED TOKEN**
Date: Tue, 08 Sep 2020 08:15:59 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: __cfduid=xxx, expires=Thu, 08-Oct-20 08:15:59 GMT; path=/; domain=.discord.com; HttpOnly; SameSite=Lax; Secure
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-ratelimit-bucket: xxx
x-ratelimit-limit: 2
x-ratelimit-remaining: 1
x-ratelimit-reset: 1599552964.170 …
```
=> Added logic to debug flows to remove tokens from output debug logs.

hikari/impl/stateful_cache.py, hikari/utilities/cache.py
Replace slow `build_entity` and `build_from_entity` methods on cache data class with abstractmethods
- [ x] I have run `nox` and all the pipelines have passed.
=> Replace slow `build_entity` and `build_from_entity` methods on cache data class with abstractmethods

hikari/api/entity_factory.py, hikari/api/rest.py, hikari/channels.py, hikari/guilds.py, hikari/impl/entity_factory.py, hikari/impl/rest.py, hikari/utilities/routes.py, tests/hikari/impl/test_entity_factory.py, tests/hikari/impl/test_rest.py, tests/hikari/test_channels.py
Add newly documented crossposting related endpoints and models.
=> Add newly documented crossposting related endpoints and models.

hikari/errors.py, hikari/impl/bot.py, hikari/impl/shard.py, tests/hikari/impl/test_shard.py
- Fixed bug where shard would not immediately close if awaiting startup in bot.
- Fixed bug where shards get requested to shutdown, but never joined, so the
event loop task reaper is what kills them.
- Removed unused and undocumented shard version parameter.
- Fixed bug in 5 second shard start backoff where close waiter was being waited
for, but within an `all_of`, which meant it would not do anything until
any shard threw an exception, or the 5 second window was up.
- Fixed bug where a single shard being closed on startup may be missed if the
shard is closed directly.
- Added more contextual debug logging to say what case caused the closure each time.
@davfsa, @FasterSpeeding please verify when you get time.
=> Fixed several bugs in shard/bot run logic.

hikari/files.py, hikari/impl/rest.py, hikari/impl/special_endpoints.py, hikari/utilities/event_stream.py, tests/hikari/impl/test_rest.py, tests/hikari/impl/test_special_endpoints.py, tests/hikari/test_files.py, tests/hikari/utilities/test_event_stream.py
=> Add syntatic sugar to `async with` classes

hikari/impl/bot.py
This will be supported until the v8 Discord API is migrated to, at
which point this will become unsupported again. You should treat this
as deprecated behaviour.
To explicitly disable intents, pass `intents=None` to the `BotApp`
constructor.
Closes #163
=> Modified `BotApp` to reallow disabling of intents.

hikari/impl/bot.py
This allows users to incrementally build upon what the base logging
config provides, should they wish to use custom levels for anything.
For example:
```py
import os
from logging.config import dictConfig
from hikari import Bot, Intents
bot = Bot(token=os.environ["BOT_TOKEN"], intents=Intents.ALL, logs="INFO")
dictConfig({
"version": 1,
"incremental": True,
"loggers": {
"hikari.gateway": {
"level": "DEBUG"
},
"hikari.ratelimits": {
"level": "TRACE_HIKARI"
},
},
})
```
...which results in output resembling...
```
D 2020-09-12 16:49:29,206 hikari.ratelimits: GET /gateway/bot is being mapped to new bucket UNKNOWN;-
T 2020-09-12 16:49:29,208 hikari.ratelimits: rate limit garbage collector started
D 2020-09-12 16:49:29,402 hikari.ratelimits: remapping GET /gateway/bot with bucket …
```
=> Added documentation about how to use Python's dictConfig incrementally.

hikari/events/typing_events.py, hikari/impl/event_factory.py, tests/hikari/events/test_typing_events.py
- GuildTypingEvent has had the `member` attribute renamed to `user`
(this is a breaking change).
- PrivateTypingEvent now has a property to get the cached user
(if possible).
=> Implemented `user` member on typing events.

hikari/events/message_events.py, tests/hikari/events/test_message_events.py
Guild message events are now documented to provide News or Text channels in output rather than just
GuildTextChannel derivatives.
Fixes #162
=> Added message author attributes to events and fixed typing.

hikari/channels.py, hikari/guilds.py, hikari/impl/entity_factory.py, hikari/impl/event_factory.py, hikari/messages.py, hikari/presences.py, hikari/users.py, hikari/utilities/cache.py, tests/hikari/test_channels.py
IntFlags are now stored on models in private fields as raw ints.
These are cast to the flag type only when accessed, which speeds up startup by some time.
=> Made flag enums lazily load, speeding up cache and event ops.

hikari/colors.py, tests/hikari/test_colors.py
Allows Color.of to accept string representations of RGB tuples, eg: `(0, 0, 0)` or `0, 0, 0`. This also works for float RGB values.
=> Allow Color.of to accept string representation of an RGB Tuple

hikari/presences.py
For some reason discord hasn't documented the fields this introduces to the activity object so this may end up being a preliminary commit.
Add "Competing" activity type
=> Add Competing activity type

hikari/events/message_events.py, hikari/utilities/ux.py
Fixes edge case where messages in guilds had a None 'author' attribute if a webhook sent the message.
=> Fixes edge case where messages in guilds had a None 'author' attribute

hikari/api/rest.py, hikari/presences.py, hikari/utilities/ux.py, tests/hikari/impl/test_shard.py, tests/hikari/utilities/test_ux.py
- Fix issues detecting and outputing new version from PyPI
#47
=> Added tests for utilities.ux

hikari/api/cache.py, hikari/events/message_events.py, hikari/events/typing_events.py, hikari/impl/stateful_cache.py, hikari/impl/stateless_cache.py, tests/hikari/events/test_typing_events.py, tests/hikari/impl/test_stateful_cache.py, tests/hikari/impl/test_stateless_cache.py, tests/hikari/utilities/test_ux.py
=> Fix inconsistecy in cache naming

hikari/api/rest.py, hikari/impl/rest.py, hikari/utilities/routes.py, tests/hikari/impl/test_rest.py
Looks like discord blocked off some integration endpoints to prevent bots from using them.
=> Remove blocked off integration endpoints

hikari/applications.py, hikari/guilds.py, tests/hikari/integration/__init__.py, tests/hikari/integration/test_users_comparison.py
This PR modifies `__hash__` and `__eq__` methods of `applications.TeamMember` and `guilds.Member` so that they are always compared according to their `user` field (other fields don't matter anymore).
Custom `__hash__` and `__eq__` had to be written, resigning from the ones generated by the `@attr` decorator(or maybe I'm wrong, I don't have experience with attrs pakage).
I'm not sure if this is the best solution as now other fields of `TeamMember` and `Member` are always ignored for every comparison, is this desired?
Another way to make the `in` operator work (see linked issue) would be to define methods like `__contains__`, `__getitem__` and so on... on the `applications.Team` class or on some new class like `applications.TeamMembers`.
These methods could then support different object …
=> Comparing applications.TeamMember with guilds.Member and users.User

README.md, hikari/snowflakes.py
'str' objects must now be cast to a Snowflake or int to be used with compatible functions.
Fixes some points in #197.
=> Snowflakeish types are no longer compatible with 'str' directly.

hikari/impl/rest.py, tests/hikari/impl/test_rest.py
Running two bots on the same token should now not error if you get ratelimited due to tracking issues.
The example case we found was running two instances of the same bot that responded to pings with a specific reaction under the same token. 
-- This should now simply log a message to say that this has happened.
=> Improved handling of bucket ratelimits in edge cases.

hikari/impl/stateful_cache.py, tests/hikari/impl/test_stateful_cache.py
Fix bad logic in clear_members_for_guild that Was erroneously trying to get the users objects after garbage collecting them
=> Fix bad logic in clear_members_for_guild

hikari/api/rest.py, hikari/impl/rest.py
Fix missing conversions for Intervlish fields in rest client
* Fix consistent by typing all "rate_limit_per_user" in the rest client as Intervalish
Closes #207
=> Fix missing conversions for Intervlish fields in rest client

hikari/api/rest.py, hikari/impl/rest.py, tests/hikari/impl/test_rest.py
Remove the delete_integration rest endpoint as it dupes leave guild now that Discord limited it to only targetting the application of the current token(Bot) within the guild.
=> Remove delete_integration rest endpoint as it now dupes leave guild

hikari/events/channel_events.py
Remove unused channel properties from channel event classes
=> Remove unused channel properties from channel event classes

examples/hello_world/hello_world.bat, examples/image_resources/image_resources.bat
I have tested this on a Windows 10 virtual machine, but would highly appreciate if you could have another look @FasterSpeeding. 
Should be as easy as opening cmd, going to the examples dir and executing `{script}.bat TOKEN` (just like the bash ones)
=> Added batch files to execute examples from cmd

.travis.yml
This is blocked until Travis implement a CPython 3.10 dev tgz distribution.
I would use python-nightly, but I will then have to amend this again later to prevent this randomly failing...
Chocolatey already has a 3.10.0-a1 distribution out, so this is ready to use for the Windows CI jobs.
=> Added CPython 3.10.0-a1 to CI.

setup.py
This is blocked until
`Programming Language :: Python :: 3.10`
is deployed to https://pypi.org/classifiers/ and https://test.pypi.org/classifiers/. Until this happens, deployments will be rejected.
=> Changed max version in setup.py and added Python 3.10 TROVE classifier.

.isort.cfg, hikari/api/rest.py, hikari/errors.py, hikari/impl/bot.py, hikari/impl/buckets.py, hikari/impl/rest.py, pipelines/nox.py, tests/hikari/impl/test_buckets.py, tests/hikari/impl/test_rest.py
This means if any REST rate limit occurs that lasts more than 60 seconds,
you will instead get a hikari.errors.RateLimitTooLongError get raised
instead which contains details of how long to back off for should you
wish to retry later.
You can disable this functionality by passing `max_rate_limit=float("inf")`
to the `hikari.impl.bot.BotApp` and `hikari.impl.rest.RESTApp` constructors
if you have a reason to not want this. The assumption is that in 99% of
cases, waiting for sustained periods of time would be confusing to the
user and lead to a poorer user experience overall, which is why this has
been implemented.
I still need to fix the tests.
Fixes #264
=> Implemented default max-retry of 60s.

docs/documentation.mako, hikari/undefined.py, tests/hikari/test_undefined.py
This should also ensure consistent pickle behaviour should anyone
attempt to pass stuff between processes (e.g. with a
ProcessPoolExecutor).
=> Redefined UNDEFINED to only use enum facade if type-checking.

.travis.yml, README.md, scripts/test-job.sh, setup.py
CPython 3.9.0 was released on Monday (two days ago, 5th October 2020).
=> Moved default Travis CI build stages to use CPython 3.9.0.

hikari/api/rest.py, hikari/impl/rest.py, tests/hikari/impl/test_rest.py
Remove include_applications from fetch_integrations as it's always true on v8
=> Remove include_applications from fetch_integrations as it's always true on v8

hikari/impl/shard.py, hikari/impl/stateful_guild_chunker.py, hikari/internal/enums.pyi, tests/hikari/impl/test_shard.py
Allow `include_presences` to be False when GUILD_PRESENCES isn't declared for shard.request_guild_members
=> Allow `include_presences` to be False when GUILD_PRESENCES isn't declared

hikari/impl/bot.py, hikari/impl/shard.py, tests/hikari/impl/test_shard.py
Errors raised by `run_once` were being suppressed causing server gateway closure errors from not propagating 
Fixes #330
=> Dont suppress errors raised by run_once

hikari/applications.py, hikari/impl/buckets.py, hikari/impl/entity_factory.py, hikari/impl/rest.py, hikari/internal/time.py, tests/hikari/impl/test_buckets.py, tests/hikari/impl/test_entity_factory.py, tests/hikari/internal/test_time.py
Switch to using `x-ratelimit-reset-after` as reset_after
* This is generally speaking more accurate than calculating this value from the `Date` header
and `X-RateLimit-Reset` headers as these seem to drift away and on add reaction endpoints
were seen to by almost a second larger than `x-ratelimit-reset-after` in some cases
(e.g 0.25 vs 0.403, 0.25 vs 0.425, 0.25 vs 1.098, 0.25 vs 0.361 and 0.25 vs 0.634)
* Make owner mandatory on application
=> Switch to using `x-ratelimit-reset-after` as reset_after

hikari/impl/bot.py
=> Fix bot.heartbeat_latency to return the average instead of the sum

hikari/api/rest.py, hikari/channels.py, hikari/impl/entity_factory.py, hikari/impl/rest.py, hikari/messages.py, hikari/urls.py, pipelines/pdoc3.nox.py, tests/hikari/impl/test_rest.py, tests/hikari/test_channels.py, tests/hikari/test_messages.py
=> Implement support for inline replies

hikari/errors.py, hikari/events/lifetime_events.py, hikari/impl/bot.py, hikari/impl/shard.py, hikari/traits.py, tests/hikari/impl/test_shard.py, tests/hikari/test_errors.py
- New error `ComponentNotRunningError` that will be raised when trying to interact with a component that is not running
- Actually closing when one of the shards has been manually shut down
- `sent_close` not being set when calling `send_close`
- Unused ratelimiter now hoocked up to prevent getting disconnected on too many requests
- `_shards` is now populated as soon as the shard object is created to be able to be used through `bot.x` on shard events
=> Several bugfixes

hikari/impl/shard.py
- Instead of raising `GatewayError` we raise `GatewayConnectionError` to cause a reconnect.
Fixes #391
=> Mediate random socket closures caused by aiohttp

hikari/api/voice.py, hikari/impl/entity_factory.py, hikari/impl/voice.py, hikari/templates.py, hikari/users.py, tests/hikari/impl/test_entity_factory.py, tests/hikari/test_errors.py, tests/hikari/test_templates.py, tests/hikari/test_users.py
=> Add more testing

hikari/channels.py, hikari/events/channel_events.py, hikari/events/guild_events.py, hikari/events/member_events.py, hikari/events/message_events.py, hikari/events/typing_events.py, hikari/guilds.py, hikari/impl/rest.py, hikari/messages.py, hikari/traits.py, tests/hikari/impl/test_rest.py, tests/hikari/test_channels.py, tests/hikari/test_guilds.py
- Removes CacheAware from RestAware
=> Modify traits to remove useless inheritance

hikari/applications.py, hikari/impl/entity_factory.py, hikari/impl/stateful_event_manager.py, tests/hikari/integration/test_users_comparison.py, tests/hikari/test_applications.py
* request presences when chunking on guild create if possible
* Make applications.TeamMember extend users.User
=> Make applications.TeamMember extend users.User plus chunk changes

hikari/channels.py, hikari/events/channel_events.py, hikari/events/message_events.py, hikari/events/typing_events.py, hikari/impl/bot.py
Fix usage/setting of bot._is_alive and invalid channel type assertions
=> Fix usage/setting of bot._is_alive and invalid channel type assertions

README.md, examples/hello_world/hello_world.py, examples/image_resources/image_resources.py, hikari/api/rest.py, hikari/channels.py, hikari/emojis.py, hikari/impl/rest.py, hikari/messages.py, hikari/users.py, pages/index.html, tests/hikari/impl/test_rest.py, tests/hikari/test_channels.py, tests/hikari/test_messages.py, tests/hikari/test_users.py
- Rename `reply_message` arg to `reply_to`
- Rename `reply_metion` arg to `mentions_reply` for consistency
- Add `mentions_reply` to `edit_message`
Closes #418
=> Seperate `reply` and `respond` in message

hikari/api/rest.py, hikari/channels.py, hikari/impl/rest.py, hikari/messages.py, hikari/users.py, tests/hikari/test_channels.py, tests/hikari/test_messages.py, tests/hikari/test_users.py
- Rename `reply_to` to `reply`
- Remove `PartialMessage.reply`
- Allow `PartialMessage.respond(reply=...)` to take in a bool to reply to self.
=> Reply cleanups

hikari/impl/bot.py, hikari/impl/event_manager.py, tests/hikari/impl/test_event_manager.py
=> Allow the event manager to run stateless-ly

hikari/impl/event_manager.py, tests/hikari/impl/test_event_manager.py
Fix generated nonces for guild chunking going over the length limit
=> Fix generated nonces for guild chunking going over the length limit

hikari/embeds.py, hikari/impl/entity_factory.py, tests/hikari/impl/test_entity_factory.py, tests/hikari/test_embeds.py
Add proxy resource to EmbedVideo and fix handling of None in embed resources.
=> Add proxy resource to EmbedVideo and fix handling of None in embed resources.

hikari/api/rest.py, hikari/impl/rest.py, tests/hikari/impl/test_rest.py
Add a member object return to rest.edit_member
=> Add a member object return to rest.edit_member

hikari/impl/entity_factory.py, tests/hikari/impl/test_entity_factory.py
Fix handling of "cover_image" in message application deserialization
=> Fix handling of "cover_image" in message application deserialization

hikari/impl/bot.py
Use sys.set_coroutine_origin_tracking_depth instead of non-existent loop.set_coroutine_tracking_depth
=> Fix how we're provisionally setting the coroutine tracking depth

hikari/guilds.py, hikari/impl/entity_factory.py, hikari/internal/cache.py, tests/hikari/impl/test_entity_factory.py
Nickname seems to be missing from gateway events if it is not set. This means we can safely set it to `None` when Discord doesn't send it
Reference: https://github.com/discord/discord-api-docs/pull/2209
=> Make nickname optional if not available

hikari/api/cache.py, hikari/guilds.py, hikari/impl/cache.py, tests/hikari/impl/test_cache.py
Allow models to be used in cache calls in place of IDs.
* Small format consistency changes to test_cache.py
=> Allow models to be used in cache calls in place of IDs.

hikari/api/special_endpoints.py, hikari/impl/special_endpoints.py
Remove partial implementation from GuildBuilder ABC
* replace attrs instance variables with settable abstract proprties
=> Remove partial implementation from GuildBuilder ABC

hikari/api/event_manager.py, hikari/audit_logs.py, hikari/event_stream.py, hikari/impl/bot.py, hikari/impl/entity_factory.py, hikari/impl/event_manager_base.py, hikari/impl/rest.py, tests/hikari/impl/test_bot.py, tests/hikari/impl/test_entity_factory.py, tests/hikari/impl/test_rest.py, tests/hikari/test_audit_logs.py, tests/hikari/test_event_stream.py
- Add app, eq, str and repr to UnrecognisedAuditLogEntryInfo
- Fix edit_webhook_message and delete_webhook_message to not use auth
- Make get_listeners(..., polymorphic=...) kwarg only
- Fix loggers used by components
=> Even more tests and fixes

hikari/internal/attr_extensions.py, hikari/internal/enums.py, hikari/internal/enums.pyi, hikari/internal/fast_protocol.py, hikari/internal/fast_protocol.pyi, hikari/traits.py, scripts/protocol_benchmark.py, tests/hikari/internal/test_typing_extensions.py
=> Rewrite `protocol.Protocol` to a typing extension

hikari/internal/enums.py, tests/hikari/internal/test_enums.py, tests/hikari/test_applications.py, tests/hikari/test_channels.py, tests/hikari/test_guilds.py, tests/hikari/test_intents.py, tests/hikari/test_invites.py, tests/hikari/test_messages.py, tests/hikari/test_presences.py, tests/hikari/test_users.py, tests/hikari/test_webhooks.py
* Fixup enums.Enum and enums.IntFlag to allow methods to be overwritten
* Add in a special case to let string enums return their value when cast to string rather than name
* Remove unnecessary/out-dated str operator tests that targeted enums which now inherit the behaviour
=> Enums consistency changes/fixes

hikari/impl/shard.py, tests/hikari/impl/test_shard.py
According to the [API's docs](https://discord.com/developers/docs/topics/gateway#heartbeating) ` The gateway may request a heartbeat from you in some situations, and you should send a heartbeat back to the gateway as you normally would` with the bit "you should send a heartbeat back to the gateway as you normally would" infers that we should be responding with a full heartbeat which is inline with how [JDA](https://github.com/DV8FromTheWorld/JDA/blob/3a9fcd0ecc88f988ac81eb2c18527283a83f12d1/src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java#L843) and [Detritus](https://github.com/detritusjs/client-socket/blob/4361739b1c824790e269db4f3abbde63fe5a5d24/src/gateway.ts#L492) handle received heartbeats and matches up with how `HEARTBEAT_ACK` is marked as Received only in the …
=> Send a full heartbeat on a heartbeat request, not just an ACK

hikari/impl/shard.py, tests/hikari/impl/test_shard.py
Fix mis-usage of PAYLOAD_ZLIB_STREAM where TRANSPORT_ZLIB_STREAM is being referred to
=> Fix mis-usage of PAYLOAD_ZLIB_STREAM where TRANSPORT_ZLIB_STREAM is being referred to

hikari/api/cache.py, hikari/impl/cache.py, tests/hikari/impl/test_cache.py
Add get_guilds_view method to cache to match get_guild
=> Add get_guilds_view method to cache to match get_guild

hikari/impl/rest.py
Fix RESTApp.acquire return typing
this needs to be typed as returning RESTClientImpl rather than the generic RESTClient abc since the ABC doesn't include being an async context manager as a part of it's interface
Without this change errors like the following are returned by MYPY when using the RESTClient
```py
hikari\impl\rest.py: note: In function "foo":
hikari\impl\rest.py:2546:16: error: "RESTClient" has no attribute "__aenter__"  [attr-defined]
async with RESTApp().acquire("OK") as client:
^
hikari\impl\rest.py:2546:16: error: "RESTClient" has no attribute "__aexit__"  [attr-defined]
async with RESTApp().acquire("OK") as client:
^
hikari\impl\rest.py:2547:9: error: Returning Any from function declared to return "GatewayBot"  [no-any-return]
return await client.fetch_gateway_bot()
^ …
```
=> Fix RESTApp.acquire return typing

hikari/embeds.py
* Mypy was incorrectly typing Embed.colour as a method (Callable[[], Optional[colors.Color]]) due to how it was aliased
Fix MYPY typing of Embed.colour alias.
Mypy was incorrectly typing Embed.colour as a method (Callable[[], Optional[colors.Color]]) due to how it was aliased as shown in the following error:
```py
hikari\embeds.py:997:1: error: Cannot assign to a method  [assignment]
Embed().colour = 42
^
hikari\embeds.py:997:18: error: Incompatible types in assignment (expression has type "int", variable has type "Callable[[], Optional[Color]]")  [assignment]
Embed().colour = 42
^
Found 2 errors in 1 file (checked 80 source files)
```
=> Fix MYPY typing of Embed.colour alias

hikari/api/rest.py, hikari/impl/rest.py, hikari/snowflakes.py, tests/hikari/impl/test_rest.py
* Enforce that at least one message is passed in the interface by adding a required positional message argument before the other_messages variable length positional argument.
* Allow the first argument to either be SnowflakeishOr[PartialMessage] or an Iterable[SnowflakeishOr[PartialMessage]] to support directly passing an iterable as this could otherwise be a pretty common mistake.
=> Improve the UX around RESTClient.delete_messages

hikari/files.py, hikari/impl/rest.py
* Try to use stream mimetype if known before defaulting to application octet stream in message create
* Default to UTF-8 charset for mimetype in Bytes instead of implicit ascii default
As a note Discord currently ignores the mimetype sent for attachments but this future proofs against any changes to how they handle them.
=> Changes around mimetype handling

.github/workflows/ci.yml, speedup-requirements.txt
=> Switch python3.10 to dev version

hikari/impl/entity_factory.py, hikari/messages.py, tests/hikari/impl/test_entity_factory.py
=> Remove preview_asset_hash as Discord no longer send it

hikari/impl/entity_factory.py, tests/hikari/impl/test_entity_factory.py
There seems to be an edge case where rtc_region won't be included in gateway events (e.g. GUILD_CREATE)
for a voice channel that just hasn't been touched since this was introduced (e.g. has been archived) which we aren't handling.
=> Fix rtc_region edge case

hikari/event_stream.py, tests/hikari/test_event_stream.py
Add missing empty slots to event stream interface
=> Add missing empty slots to event stream interface

pipelines/safety.nox.py
This avoids safety erroring due to https://github.com/pypa/pip/pull/9827 by ensuring an up to date pip version is installed.
=> Upgrade pip before running safety

hikari/api/event_factory.py, hikari/events/channel_events.py, hikari/events/member_events.py, hikari/events/role_events.py, hikari/impl/event_factory.py, hikari/impl/event_manager.py, tests/hikari/impl/test_event_factory.py, tests/hikari/impl/test_event_manager.py
Add tests for event unmarshalling
* Add "old_x" attributes to InviteDeleteEvent, MemberDeleteEvent and RoleDeleteEvent
* Make some imports type checking only in event factory
=> Add tests for event unmarshalling

hikari/impl/entity_factory.py, hikari/internal/enums.py
Ensure Flags only handles int internally
* Avoid redundant casts in the entity factory
=> Ensure Flags only handles int internally

hikari/impl/buckets.py, hikari/impl/rate_limits.py, hikari/impl/rest.py, hikari/impl/special_endpoints.py, hikari/internal/routes.py, tests/hikari/impl/test_buckets.py, tests/hikari/impl/test_rate_limits.py, tests/hikari/impl/test_rest.py
- Move lock to per-bucket lock
- Don't acquire global_rate_limit when not using authentication
=> Improve request rate limiting

hikari/emojis.py, hikari/messages.py, hikari/presences.py, hikari/users.py
UnicodeEmoji should be hashable
* Also add in hashing and equality to Attachment
* Fix hashing/equality behaviour on PartialMessage and MemberPresence
* Remove overkill attrs call on User and PartialUser abcs
=> UnicodeEmoji should be hashable

tests/hikari/impl/test_rest.py, tests/hikari/test_users.py, tests/hikari/test_webhooks.py
=> Use `is` for object equity in tests

hikari/messages.py, tests/hikari/test_messages.py
Convert Message.link property to Message.make_link function
This change is necessary since the lib can't always work out whether a message is in a DM or guild and the old Message.link property would default to assuming it's DM which is incorrect behaviour. This would have primarily effected applications which are REST-only or cache-less/not caching channels.
=> Convert Message.link property to Message.make_link function

hikari/impl/special_endpoints.py
Let OwnGuildIterator rely on the default limit
This means that it'll now return 200 guilds per request rather than 100.
=> Let OwnGuildIterator rely on the default limit

.github/workflows/ci.yml, pipelines/twemoji.nox.py, scripts/deploy-pages.sh, scripts/deploy.sh, scripts/deploy_webhook.sh, scripts/increase_version_number.py
Installing hikari from the repository does not work anymore as of [PEP 517](https://www.python.org/dev/peps/pep-0517/). Due to this we have relied on editable mode (`-e`) to bypass that. With [PEP 660](https://www.python.org/dev/peps/pep-0660/), right around the corner, this will break, so we need a better alternative.
This PR will fix that by setting a new default version that will update with every release.
=> Set repository version to latest and update on new release

hikari/guilds.py, hikari/impl/entity_factory.py, hikari/invites.py, tests/hikari/impl/test_entity_factory.py, tests/hikari/test_guilds.py
*Note: Even tho this is marked as breaking, this is just because it will break any bot pulling from master. `is_nsfw` never got to be deployed in a proper version of the lib*
=> Replace Guild.is_nsfw with Guild.nsfw_level

hikari/errors.py, hikari/impl/bot.py, hikari/impl/rest.py, hikari/impl/shard.py, hikari/impl/special_endpoints.py, hikari/traits.py, tests/hikari/impl/test_bot.py, tests/hikari/impl/test_rest.py, tests/hikari/impl/test_shard.py, tests/hikari/test_errors.py
* Rename ComponentNotRunningError to ComponentStateConflictError 
* Plus replace some usages of RuntimeError for functions which cannot be called while a component is still alive with ComponentStateConflictError
* Replace HTTPClientClosedError with ComponentStateConflictError
=> ComponentNotRunningError error refactors

hikari/impl/rest.py, hikari/internal/routes.py, tests/hikari/impl/test_rest.py
https://discord.com/developers/docs/resources/channel#edit-channel-permissions
=> Fix edit_permission_overwrites route using wrong method

hikari/api/rest.py, hikari/impl/rest.py, tests/hikari/impl/test_rest.py
Allow a datetime to be passed for request_to_speak
=> Allow a datetime to be passed for request_to_speak

hikari/impl/shard.py
I have observed after a personal outage that the shard will not reset the backoff if nothing went wrong, causing it to later wait the maximum backoff in the future:
Between detecting we have an invalid session and then acquiring a new one, it should have waited the first backoff, not the maximum one.
=> Reset shard backoff if nothing went wrong when shutting down

hikari/files.py
This simple PR fixes an issue where a 0-byte attachment is sent as opposed to the actual attachment. This happens because the *wrapped bytes* object has been consumed by `unwrap_bytes` function so that EOF's reached, yet it's passed again on to `hikari.Bytes`.
Context: https://discord.com/channels/574921006817476608/727982024660615198/849576917891285024
=> Pass in the unwrapped bytes instead

hikari/events/message_events.py, hikari/messages.py, tests/hikari/events/test_message_events.py
This will provide more consistency as well as fix .author raising and error when a webhook sends/edits a message
=> Separate member and author on GuildMessage* events

hikari/internal/time.py, tests/hikari/hikari_test_helpers.py, tests/hikari/impl/test_shard.py, tests/hikari/internal/test_time.py
=> Split iso8601_datetime_string_to_datetime into slow and fast

hikari/api/rest.py, hikari/channels.py, hikari/messages.py, hikari/users.py
Remove outdated gateway create message limit
This was removed in https://github.com/discord/discord-api-docs/commit/5f4decb7c488064d469188bc631e23fef7adf6ae#diff-160acb4654c611c67c4ee46b2ce5dda2be82212af8d1d00cd0256ef6edda1e95
=> Remove outdated gateway related create message limit warnings

hikari/applications.py, hikari/channels.py, hikari/embeds.py, hikari/guilds.py, hikari/snowflakes.py, tests/hikari/test_applications.py, tests/hikari/test_channels.py, tests/hikari/test_guilds.py
* remove settability from Unique.id's interface 
* Switch GuildChannel.shard_id from a try except to a trait bound instance check
=> remove settability from Unique.id's interface + small refactor

hikari/api/cache.py, hikari/applications.py, hikari/config.py, hikari/guilds.py, hikari/impl/bot.py, hikari/impl/cache.py, hikari/impl/rest.py, hikari/internal/cache.py, hikari/users.py, tests/hikari/impl/test_bot.py, tests/hikari/impl/test_cache.py, tests/hikari/impl/test_rest.py, tests/hikari/test_applications.py, tests/hikari/test_guilds.py, tests/hikari/test_users.py
introduce REST filled DM Channel ID cache resource
* Remove caching DM channel objects on user objects in favour of new cache resource
=> introduce REST filled DM Channel ID cache resource

hikari/impl/bot.py, tests/hikari/impl/test_bot.py
Delay initialisation of BotApp._closing_event and use it as ._closed
* This also solves the potential issue where BotApp._closed was never re-set to `False` once a bot was re-started
This contributes to #625
=> Delay initialisation of BotApp._closing_event and use it as ._closed

hikari/api/rest.py, hikari/impl/rest.py, tests/hikari/impl/test_rest.py
Add a token type property to the rest interface to allow for token introspection
=> Add a token type property to the rest interface to allow for token introspection

hikari/api/event_manager.py, hikari/impl/bot.py, hikari/impl/event_manager_base.py, tests/hikari/impl/test_event_manager_base.py
=> Remove return from subscribe calls

hikari/api/rest.py, hikari/channels.py, hikari/impl/rest.py, hikari/messages.py, hikari/users.py, hikari/webhooks.py, tests/hikari/test_channels.py, tests/hikari/test_messages.py, tests/hikari/test_users.py
Add sending multiple embeds on create and edit message
* Fix bug where execute_webhook(embeds=None) on the standard REST client implementation would lead to erroneous behaviour
* Fix bug where Message.respond(reply=False) would try to respond to a message with the ID 0
=> Add sending multiple embeds on create and edit message

hikari/impl/bot.py, hikari/impl/shard.py, tests/hikari/impl/test_bot.py, tests/hikari/impl/test_shard.py
Rework bot.close to fix lifetime events not always dispatching.
Removed `force` attribute in favour of always gracefully shutting down
=> Fix lifetime events not dispatching

hikari/internal/ux.py, tests/hikari/internal/test_ux.py
Default to ANSI colour for Windows Terminal + logic refactor
* better fit clicolor's standard behaviour by interpreting os.getenv("CLICOLOR") == "0" as an instruction that colours shouldn't be used rather than passing over it as undefined
* Switch over to patching os.environ in test cases rather than relying on the call order of os.getenv
=> Default to ANSI colour for Windows Terminal + logic refactor

hikari/internal/reflect.py, tests/hikari/internal/test_reflect.py
Use Signature's eval_str argument in resolve_signature (3.10+ specific)
=> Use Signature's eval_str argument in resolve_signature (3.10+ specific)

hikari/impl/event_manager_base.py, tests/hikari/impl/test_event_manager_base.py
Only resolve type hints in @listen when necessary
(This avoids errors being raised by reflect.resolve_signature when the event type was explicitly provided)
* Allow for listeners with other defaulted arguments
=> Only resolve type hints in @listen when necessary

hikari/api/entity_factory.py, hikari/api/rest.py, hikari/applications.py, hikari/audit_logs.py, hikari/channels.py, hikari/events/channel_events.py, hikari/impl/entity_factory.py, hikari/impl/rest.py, hikari/webhooks.py, tests/hikari/impl/test_entity_factory.py, tests/hikari/impl/test_rest.py, tests/hikari/test_channels.py, tests/hikari/test_webhooks.py
Split Webhook into type specific definitions
Closes #608
=> Split Webhook into type specific definitions

hikari/api/rest.py, hikari/api/voice.py, hikari/impl/bot.py, hikari/impl/event_manager.py, hikari/impl/rest.py, hikari/impl/shard.py, hikari/impl/voice.py, tests/hikari/impl/test_bot.py, tests/hikari/impl/test_event_manager.py, tests/hikari/impl/test_rest.py, tests/hikari/impl/test_shard.py, tests/hikari/impl/test_voice.py
* This adds an is_alive property to Voice component along with ComponentStateConflictError cases in the main implementation to avoid erronous behaviour from connections being added after it stops tracking voice events.
* ~~This also explicitly raises ComponentStateConflictError in BotApp if it's already been used instead of letting the rest client raise it on fetch_gateway_bot and documents the fact that BotApp is one use~~
=> Make voice and rest components multi-use

hikari/api/special_endpoints.py, hikari/impl/special_endpoints.py, tests/hikari/impl/test_special_endpoints.py
Add setting flags for deferred responses
=> Add setting flags for deferred responses

hikari/api/cache.py, hikari/api/rest.py, hikari/api/special_endpoints.py, hikari/applications.py, hikari/audit_logs.py, hikari/channels.py, hikari/events/channel_events.py, hikari/events/message_events.py, hikari/events/typing_events.py, hikari/guilds.py, hikari/impl/cache.py, hikari/impl/entity_factory.py, hikari/impl/rest.py, hikari/impl/special_endpoints.py, hikari/invites.py, hikari/templates.py, hikari/voices.py, hikari/webhooks.py, tests/hikari/test_channels.py, tests/hikari/test_webhooks.py
* Rename TextChannel to TextableChannel + add TextableGuildChannel
This fixes some typing issues where GuildTextChannel was being asserted and typed in a few scenarios where GuildNewsChannel and in the future thread channels would also be expected while also trying to lay out a better structure for handling guild channels which handle messages in-order to lower the chance of this kind of issue recurring
* Add WebhookChannelT union and WebhookChannelTypes to channels.py 
This is used in the type hint for create_webhook, fetch_channel_webhooks, and edit_webhook in place of TextableChannel in-order to account for the fact that webhooks cannot be directly attached to thread channels.
* Improve typing for edit voice state rest methods to use GuildVoiceChannel rather than PartialChannel
This is …
=> Add TextableGuildChannel mixin class + improve typing around guild text channel operations

hikari/errors.py, hikari/internal/data_binding.py, hikari/internal/net.py, tests/hikari/internal/test_net.py, tests/hikari/test_errors.py
This adds the loosely documented "errors" mapping on some error responses (see https://discord.com/developers/docs/reference#error-messages for ref) to BadRequestError
=> Improve 50035 400 error reprs

hikari/interactions/commands.py
Command options only have 1 value
=> CommandInteractionOption typing fix

hikari/api/rest.py, hikari/emojis.py, hikari/events/reaction_events.py, hikari/guilds.py, hikari/impl/entity_factory.py, hikari/impl/event_factory.py, hikari/impl/rest.py, hikari/internal/cache.py, hikari/messages.py, tests/hikari/events/test_reaction_events.py, tests/hikari/impl/test_entity_factory.py, tests/hikari/impl/test_event_factory.py, tests/hikari/impl/test_rest.py, tests/hikari/test_emojis.py, tests/hikari/test_messages.py
Improve typing of Emoji classes
* Make CustomEmoji (and therefore also Emoji) more strict
* Flatten down reaction event models and guild WelcomeChannel + document special case behaviour on them directly.
* Remove Emoji.is_mentionable as it is no longer relevant.
This also removes cases where CustomEmoji.filename, CustomEmoji.mention, CustomEmoji.url_name and CustomEmoji.url would return potentially invalid data if a field was None.
* For CustomEmoji.mention there was a partner CustomEmoji.is_mentionable field which was probably intended to indicate whether CustomEmoji.mention would return data which is guaranteed to be valid or not but this behaviour wasn't documented.
* When CustomEmoji.url_name would return `"None:{emoji.id}"` while this technically works under current behaviour (as the …
=> Improve typing/strictness of Emoji classes

hikari/impl/bot.py, tests/hikari/impl/test_bot.py
- Some people were getting confused as to why bot.close was getting called 2+ times
=> Split bot.close into internal and external functions

.github/workflows/ci.yml
Github Actions seems to detect a skipped job as a successful one, we don't want that
=> Mark ci-done as failed when past jobs failed

hikari/guilds.py, hikari/impl/entity_factory.py, tests/hikari/impl/test_entity_factory.py
With the addition of the new relay infrastructure, this will always be None except for the largest of guilds
=> Remove the default max presences of 25000

hikari/invites.py, hikari/webhooks.py, tests/hikari/test_webhooks.py
=> Fix CDN properties not ending with "_url"

hikari/api/interaction_server.py, hikari/events/interaction_events.py, hikari/files.py, hikari/impl/interaction_server.py, hikari/impl/rest_bot.py, hikari/internal/ed25519.py, hikari/internal/mentions.py
=> Consistency fixes for `__all__` usages

hikari/api/event_factory.py, hikari/events/interaction_events.py, hikari/impl/event_factory.py, hikari/impl/event_manager.py, tests/hikari/events/test_interaction_events.py, tests/hikari/impl/test_event_factory.py, tests/hikari/impl/test_event_manager.py
This pr removes events related to application commands as a discord developer said these events aren't supposed to sent to  bots. Source:  https://github.com/discord/discord-api-docs/pull/3691
=> Remove application command events

CHANGELOG.md, hikari/api/rest.py, hikari/guilds.py, tests/hikari/test_guilds.py
This pull request adds a few methods onto `hikari.guilds.PartialGuild`.
- fetch_sticker
- fetch_stickers
- create_sticker
- edit_sticker
- delete_sticker
In addition, there were some mistakes in `hikari.api.rest` docstrings for the sticker methods which have been corrected.
Related to #400
=> Add sticker methods to PartialGuild

CHANGELOG.md, hikari/api/rest.py, hikari/guilds.py
This PR removes a duplicate raise from rest.fetch_channel docstrings.
=> Remove duplicate raise type in docstrings

hikari/impl/rest.py, tests/hikari/impl/test_rest.py
Move away from deprecated "reason" body field on ban member
=> Move away from deprecated "reason" body field on ban member

hikari/events/reaction_events.py, tests/hikari/events/test_reaction_events.py
Add is_for_emoji methods to relevant reaction events, as suggested by @tandemdude
=> Add is_for_emoji methods to the relevant reaction events

changes/783.bugfix.md, hikari/events/message_events.py, hikari/impl/entity_factory.py, hikari/messages.py, tests/hikari/events/test_message_events.py, tests/hikari/impl/test_entity_factory.py, tests/hikari/test_messages.py
Thanks to @Le0Developer for bringing up the initial issue of  `is_webhook` always being `True` for `MessageUpdateEvent` in the Discord server.
This had me investigate and opened up a whole can of worms where I found inconsistencies and bugs in code and documentation fixes.
- Fix the use of `typing.Optional` where `undefined.UndefinedOr` should have been used.
- Remove trying to acquire `guild_id` from the cached channel on `PartialMessage`
- Instead, clearly document the issue Discord imposes by not sending the `guild_id`
- `is_webhook` can now return `undefined.UNDEFINED` if the information is not available
- Fix logic in `is_human` to account for the changes in types
- Set `PartialMessage.member` to `undefined.UNDEFINED` when Discord edit the message to display an embed/attachment
None
=> Improve typing for messages and message update methods

changes/788.bugfix.md, hikari/embeds.py
Thanks to @zykrahgaming for pointing out this bug to me on Discord
The issue itself was embed resources wrapping around other embed resources (you can achive this by passing the footer icon of one embed to `set_footer` in another), which lead the deserialize process to count it as 2 resources, thus uploading twice
None
=> Prevent double linking embed resources, which causes them to upload twice

CONTRIBUTING.md, changes/804.doc.md, changes/804.feature.md, hikari/api/event_manager.py, hikari/api/special_endpoints.py, hikari/guilds.py, hikari/impl/bot.py
This PR adds various fixes and clarifications to the documentation.
- Adds the add_component method to `api.special_endpoints.ActionRowBuilder`
- Adds `nox` and `towncrier` requirements to `CONTRIBUTING.md`
- Adds docstrings to the remaining undocumented `GatewayBot` methods
N/A
=> Documentation additions and fixes

hikari/api/cache.py, hikari/api/entity_factory.py, hikari/config.py, hikari/events/base_events.py, hikari/impl/bot.py, hikari/impl/cache.py, hikari/impl/entity_factory.py, hikari/impl/event_factory.py, hikari/impl/event_manager.py, hikari/impl/event_manager_base.py, tests/hikari/impl/test_bot.py, tests/hikari/impl/test_cache.py, tests/hikari/impl/test_entity_factory.py, tests/hikari/impl/test_event_factory.py, tests/hikari/impl/test_event_manager.py, tests/hikari/impl/test_event_manager_base.py
This change looks into how we may be able to avoid deserializing event data when it isn't being listened to or used to set state to lower the inherent strain of shard dispatch. While intents can help with this by lowering the amount of events a bot receives, intents can't always be used to prevent unwanted events as some events just aren't covered by it and some of it's categories (such as GUILDS) are broad enough to have the potential to still lead to unnecessary events being received.
Another benefit this has over intents is that while intents are behaviour that's statically defined for the entire runtime of a shard, the behaviour of this filtering is dynamic and will shift based on what's being listened for and cached.
Due to the broad scope of the GUILD_CREATE and GUILD_UPDATE events, …
=> Start filtering events before unmarshalling

changes/911.bugfix.md, hikari/impl/event_manager_base.py
=> Fix logic for asserting listeners to not error when using defaults for other arguments

changes/912.bugfix.md, hikari/impl/special_endpoints.py
Fix ActionRowBuilder inner-type assertion
=> Fix ActionRowBuilder inner-type assertion

CHANGELOG.md
=> EventStream is a context manager not menu (c-log)

changes/928.bugfix.md, hikari/impl/rest.py, tests/hikari/impl/test_rest.py
=> Fix reposition_roles using the wrong route

changes/920.feature.md, hikari/commands.py, hikari/impl/entity_factory.py, tests/hikari/impl/test_entity_factory.py
Add min_value and max_value to CommandOption. 
Reference: https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-structure
=> Add min_value and max_value to CommandOption

changes/931.bugfix.md, changes/idk.bugfix.md, hikari/internal/routes.py
Fix ROLE_ICON cdn route as to not always include ".png" before the file type extension
=> Fix ROLE_ICON cdn route

scripts/deploy.sh
Thanks to @Jonxslays for pointing this out to me. Looks like this line was never running due to a missing space
=> Fix logic to ensure no CHANGELOG files exist

changes/930.bugfix.md, hikari/internal/routes.py, hikari/stickers.py, tests/hikari/test_stickers.py
=> Fix PartialSticker.image_url not passing the hash as a string

changes/940.feature.md, hikari/api/rest.py, hikari/guilds.py, hikari/impl/entity_factory.py, hikari/impl/rest.py, hikari/internal/cache.py, hikari/permissions.py, tests/hikari/impl/test_cache.py, tests/hikari/impl/test_entity_factory.py, tests/hikari/impl/test_rest.py, tests/hikari/integration/test_users_comparison.py, tests/hikari/test_guilds.py, tests/hikari/test_permissions.py
Implements member `communication_disabled_until` and the new `MODERATE_MEMBERS` permission.
=> Implement member timeout

hikari/commands.py
Fixes incorrect docstrings for CommandOption.min_value and CommandOption.max_value
=> Fix docstrings for CommandOption.min|max_value

changes/954.bugfix.md, changes/idk.bugfix.md, hikari/impl/bot.py, tests/hikari/impl/test_bot.py
Fix deprecation warning raised by out of loop asyncio.gather calls
=> Fix deprecation warning raised by out of loop asyncio.gather calls

changes/876.bugfix.md, hikari/api/interaction_server.py, hikari/api/special_endpoints.py, hikari/impl/interaction_server.py, hikari/impl/rest_bot.py, hikari/impl/special_endpoints.py
Allow for more relaxed arg type fallback in some overloaded signatures
Closes #875
=> Allow for more relaxed arg type fallback in some overloaded signatures

hikari/api/interaction_server.py, hikari/impl/interaction_server.py, hikari/impl/rest_bot.py
This union fallback was erroneously added in while adding in fallback types for getting methods which had overloaded behaviour based on unions and adding this here has a different unwanted effect (removing the Interaction type to response builder type(s) restriction).
=> Bring back more concise typing for set_listener

changes/955.feature.md, changes/idk.feature.md, hikari/api/rest.py, hikari/applications.py, hikari/impl/rest.py, hikari/internal/routes.py, tests/hikari/impl/test_rest.py
=> Implement fetch my member

requirements.txt
Looks like the issue was fixed with the release of 6.0.2, but dependabot catch it an open the pr, so I will beat it to it :)
Followup for #979
=> Bump multidict to ~=6.0

changes/982.bugfix.md, hikari/users.py
Similar to one of the changes in #933, here I forgot to add `auto_attribs=False`, which lead to all the attributes being reset to their defaults, which messed up `__eq__` along with possibly more functionality.
This time I took the extra time to look for more uses of this and have not been able to find any
Closes #980
=> Fix reset of attributes in UserImpl

changes/984.feature.md, changes/idk.feature.md, hikari/api/event_factory.py, hikari/impl/event_factory.py, tests/hikari/impl/test_event_factory.py
Default old_x arguments to None in the event factory
=> Default old_x arguments to None in the event factory

changes/975.feature.md, hikari/guilds.py, hikari/users.py, tests/hikari/test_guilds.py, tests/hikari/test_users.py
It is somewhat tedious to get an `avatar_url` that is guaranteed to always exist, this property aims to rectify this issue, and simplify getting avatars somewhat.
=> Add display_avatar_url property for Member & User

changes/971.feature.md, hikari/api/rest.py, hikari/impl/rest.py, hikari/interactions/base_interactions.py, tests/hikari/impl/test_rest.py, tests/hikari/interactions/test_base_interactions.py
Adds the ability to pass attachments with `create_initial_response`
=> Add ability to send attachments in an interaction initial response

pipelines/nox.py
Mostly just a suggestion since this doesn't seem helpful to most ppl running it locally and under the rare case that their changes break doc gen this'll still be flagged up by pipelines when they open a PR
=> Remove pages and safety from the default nox sessions

hikari/impl/shard.py, tests/hikari/impl/test_shard.py
=> Fix `$browser` to use the correct format

hikari/api/rest.py, hikari/impl/rest.py
This should better clarify that the deprecated methods still only create slash command (builders) and only point towards the relevant new slash command method.
=> Improve deprecation notices for rest cmd methods

hikari/internal/collections.py, tests/hikari/hikari_test_helpers.py, tests/hikari/impl/test_buckets.py, tests/hikari/impl/test_event_manager_base.py, tests/hikari/impl/test_rate_limits.py, tests/hikari/impl/test_rest.py, tests/hikari/internal/test_aio.py, tests/hikari/internal/test_collections.py
Some people were complaining that the tests where taking too long to run, so this goes out for them :P
```
Before: 11s 264ms
After: 996ms
```
```
Before: 2min 14s
After: 1min 49s
```
#
This pr also removes `TimedCacheMap`, as while optimizing the tests for it I noticed that it wasnt being used anywhere. This removal can be moved to a separate pr if needed. Since its considered internal detail, I dont think there is a need for deprecation or breaking changelog
Closes #1010
=> Optimize tests and fix flaky tests to reduce race conditions

changes/1014.bugfix.md, hikari/impl/shard.py, tests/hikari/impl/test_shard.py
- Improve `GatewayShard.is_alive` detection
- Cleanup code for `GatewayTransport.send_close`
Closes #1011
=> Attempt to reconnect on a gateway TimeoutError

changes/1021.feature.md, hikari/intents.py, tests/hikari/impl/test_shard.py
Message content intent will be required for verified applications starting April 30th 2022, this change adds them to hikari.
https://support-dev.discord.com/hc/en-us/articles/4404772028055
https://github.com/discord/discord-api-docs/discussions/4510
=> Add MESSAGE_CONTENT intent

hikari/channels.py, pipelines/config.py, pipelines/pyright.nox.py
This is unnecessary now that the pypi wrapper for pyright locks the default pyright version it uses
=> Remove unnecessary pyright version lock

changes/1023.bugfix.md, hikari/api/shard.py, hikari/impl/bot.py, hikari/impl/shard.py, tests/hikari/impl/test_bot.py, tests/hikari/impl/test_rest.py, tests/hikari/impl/test_shard.py, tests/hikari/impl/test_voice.py
Properly close when not started correctly.
Cleans up errors with "Unclosed client session" and anything else the event loop might want to throw
=> Properly close when not fully started

changes/1057.feature.md, hikari/channels.py, hikari/guilds.py, tests/hikari/test_channels.py
This PR adds `get_guild()` to `hikari.GuildChannel`.
=> Add get_guild() to hikari.GuildChannel

pyproject.toml
This replaces the current behaviour (where async tests will just be ignored if pytest-asyncio isn't installed) with getting a loud error if pytest-asyncio isn't installed.
=> Require pytest-asyncio to run pytest

changes/1066.bugfix.md, hikari/impl/entity_factory.py
- Fixes the value for options with ATTACHMENT type being of `str` instead of `Snowflake`
=> Fix incorrect type for ATTACHMENT option values

hikari/impl/shard.py, tests/hikari/impl/test_shard.py
=> Fix handling of when the first zlib message is complete

tests/hikari/internal/test_ux.py
Not a huge speedup, but was adding 1s (0.25 * 4)
=> Speedup tests by mocking sleep calls

changes/1989.bugfix.md, hikari/guilds.py
`GuildFeature.MORE_STICKERS` has the wrong value.
=> fix GuildFeature.MORE_STICKERS

changes/1990.feature.md, hikari/__init__.py, hikari/__init__.pyi, hikari/api/rest.py, hikari/guilds.py, hikari/impl/entity_factory.py, hikari/impl/rest.py, hikari/interactions/command_interactions.py, hikari/interactions/component_interactions.py, hikari/locales.py, hikari/templates.py, hikari/users.py, tests/hikari/impl/test_entity_factory.py
Add `hikari.locales.Locale` enum. (possibly breaking change?)
Not sure where else to put it, tell me if there's a better place for it. Open for feedback :)
=> add hikari.locales.Locale

changes/1086.breaking.md, hikari/api/rest.py, hikari/impl/entity_factory.py, hikari/voices.py, tests/hikari/impl/test_entity_factory.py
Documentation change PR: https://github.com/discord/discord-api-docs/pull/3908
---
Considering removing `fetch_guild_voice_regions` and keeping `fetch_voice_regions`, as there is no difference between them anymore
=> Remove `VoiceRegion.is_vip` due to Discord no longer sending it

changes/idk.bugfix.md, changes/idk.feature.md, hikari/api/entity_factory.py, hikari/api/event_manager.py, hikari/events/base_events.py, hikari/impl/entity_factory.py, hikari/impl/event_manager.py, hikari/impl/event_manager_base.py, tests/hikari/impl/test_entity_factory.py, tests/hikari/impl/test_event_factory.py, tests/hikari/impl/test_event_manager.py, tests/hikari/impl/test_event_manager_base.py
=> Improve filtering by using per event bitmasks

flake8-requirements.txt
Flake8-html already has a fix for this on master, so we just need to wait for a release (https://github.com/lordmauve/flake8-html/commit/edef580c6d5e0ccb3ab54aa31b42b4359f7b9235)
=> Temporarily freeze jinja2 to 3.0.3

hikari/impl/shard.py, tests/hikari/impl/test_shard.py
From testing, this doesnt seem to affect anything at all and just sends payloads that Discord will ignore as well as close unexpectedly on us. Further testing (running constantly for at least 48h) is needed, but I dont see why we should have these enabled.
Would greatly appreciate if someone could try out this PR in their bot and lmk how it goes
=> Disable ws autoclose

changes/1103.feature.md, hikari/api/event_manager.py, hikari/impl/bot.py, hikari/impl/event_manager_base.py, tests/hikari/impl/test_event_manager_base.py
This pull requests allows passing multiple events to the listen decorator.
Alternatively, a Union can be used in the type hint to achieve the same thing.
```py
@bot.listen(hikari.GuildAvailableEvent, hikari.GuildJoinEvent)
async def on_guild_available(event: ...) -> None:
...
@bot.listen()
async def on_start(event: hikari.StartingEvent | hikari.StartedEvent) -> None:
...
```
Flake8 session is failing - but it was on master before I touched anything.
=> Allow passing multiple events to the @listen decorator

changes/1048.feature.md, hikari/api/interaction_server.py, hikari/api/special_endpoints.py, hikari/impl/interaction_server.py, hikari/impl/special_endpoints.py, hikari/internal/data_binding.py, tests/hikari/impl/test_interaction_server.py, tests/hikari/impl/test_rest.py, tests/hikari/impl/test_special_endpoints.py
Opening this as a draft just to keep track of it somewhere since this responses over 150 KiB seem to be automatically failed/rejected so...
=> Add multipart responses to the interaction server

hikari/internal/ux.py, tests/hikari/internal/test_ux.py
=> Don't close low-level stdout stream when printing banner

changes/1164.breaking.md, hikari/api/special_endpoints.py, hikari/errors.py, hikari/impl/entity_factory.py, hikari/impl/rest.py, hikari/impl/special_endpoints.py, hikari/internal/data_binding.py
Returning JSONObjectBuilder introduces issues for anybody who's overriding these methods as they'd have to type their return methods as JSONObjectBuilder which is an internal type.
And  MutableMapping is preferred over JSONObject for a return type
=> Make sure build methods are typed consistently

docs/patched_pdoc.py
Use right roles in `objects.inv` file, in documentation, so `intersphinx` can normally access them.
See #1173, https://github.com/hikari-py/hikari/pull/1118#discussion_r884153829 and https://sphobjinv.readthedocs.io/en/latest/syntax.html.
=> Use right roles in `objects.inv` file

changes/1207.breaking.md, hikari/guilds.py, tests/hikari/test_guilds.py
Discord mentions should not have the `!` bang anymore per deprecation by Discord.
=> Remove case of bang (`!`) from `Member.mention` property

changes/1222.doc.md, hikari/api/rest.py
fixed `fetch_message` docstring
=> fixed typo in `fetch_message` docstring

changes/1221.feature.md, hikari/channels.py, tests/hikari/test_channels.py
Discord allows mentioning of all channels through the `<#id>` syntax, so it makes sense to move the mention property to the base class.
=> move mention property from `GuildChannel` to `PartialChannel`

changes/1247.bugfix.md, hikari/internal/time.py, tests/hikari/internal/test_time.py
Change to a more precise and reliable snowflake datetime conversion to fix float precision issues.
Special thanks to @rexor12 for investigating and providing the initial fix!
=> More precise snowflake datetime conversion

hikari/interactions/base_interactions.py
This is not allowing me to properly see the documentation in PyCharm for.. whatever reason. I believe Pylance for my env is not recognising it because of that one nutty space.
=> docs: fix intellisense relation for `DeferredResponseTypesT`

changes/1259.bugfix.md, hikari/impl/rest.py, tests/hikari/impl/test_rest.py
`reposition_channels` currently doesn't work, as it uses the `POST_GUILD_CHANNELS` route instead
of the `PATCH_GUILD_CHANNELS` route.
=> Fix endpoint used in reposition_channels

changes/1263.doc.md, hikari/channels.py
Fix the missing `id` parameter in the example usage of `channels.PermissionOverwrite`.
=> Fix PermissionOverwrite Example

hikari/impl/rest.py
Wrong version was used in error.
=> Fix incorrect deprecation version for `RESTClientImpl.edit_permission_overwrites`

pipelines/format.nox.py
=> Remove codespell from reformat-code

changes/1273.breaking.md, hikari/files.py, pyproject.toml, tests/hikari/test_files.py
- Also cleans up code for reading using ThreadPool executors
- It is more efficient to use a threadpool executor and it makes no sense to use anything else
- Due to the nature of process pool, were were also not able to perform proper chunking when reading off the file
=> Remove support for ProcessPoolExecutor executor when reading files

.github/workflows/ci.yml
Ill keep everything else added by #847, as we do technically support 3.11 and everything works fine, the only issue is just a cpython bug when running pytest. Its what happens with dev versions :)
ref: https://github.com/python/cpython/issues/97002
=> Temporarily disable testing in 3.11-dev due to CPython crash

changes/1289.deprecation.md, hikari/api/cache.py, hikari/internal/cache.py, tests/hikari/internal/test_cache.py
=> Deprecate CacheView.iterator in favour of using itertools

MANIFEST.in
Sdist should be freestanding bootstrapable distributions of the python package. In #1000 requirement files were removed from the MANIFEST.in making sdists no longer freestanding. I discovered this when I attempted to use nix-community/poetry2nix in a project which prefer's building from sdists.
Closes #1323
=> Bundle requirement files with source distribution 

tests/hikari/internal/test_signals.py
=> Fix raise_interrupt test failing on some platforms

changes/1355.feature.md, hikari/users.py, tests/hikari/impl/test_entity_factory.py
Adds the new [Active Developer](https://support-dev.discord.com/hc/en-us/articles/10113997751447) badge to the list of available user flags.
=> Add new ACTIVE_DEVELOPER flag to UserFlags

changes/1386.bugfix.md, hikari/channels.py, hikari/impl/entity_factory.py, tests/hikari/impl/test_entity_factory.py, tests/hikari/test_channels.py
`is_nsfw` now also defaults to `False` when excluded from the payload. It seems like Discord will always send the nsfw field when it is set to `True`, but randomly exclude it when its `False`.
Closes #1328
=> Remove incorrect `is_nsfw` from threads

changes/1434.bugfix.md, hikari/internal/ux.py, tests/hikari/internal/test_ux.py
=> Properly close unclosed file descriptor when reading banner

changes/1430.feature.md, hikari/api/entity_factory.py, hikari/api/rest.py, hikari/channels.py, hikari/errors.py, hikari/guilds.py, hikari/impl/entity_factory.py, hikari/impl/rest.py, hikari/internal/ux.py, tests/hikari/impl/test_entity_factory.py, tests/hikari/impl/test_rest.py, tests/hikari/test_channels.py, tests/hikari/test_errors.py, tests/hikari/test_guilds.py
=> Add support for guild forums

.github/workflows/ci.yml
Looks like windows is the odd-one-out again. https://github.com/actions/runner-images/issues/6668.
Been sitting on this for a while now so they would hopefully fix it, but it looks like its intended behavior.
=> Run CI tests on `bash` to exit fast on error on Windows

changes/1459.feature.md, hikari/impl/bot.py, hikari/impl/rest_bot.py, hikari/internal/ux.py, tests/hikari/impl/test_bot.py, tests/hikari/impl/test_rest_bot.py, tests/hikari/internal/test_ux.py
This PR adds the ability to suppress optimization warnings by passing `suppress_optimization_warning=True` to the `GatewayBot` and `RESTBot` constructors.
Closes #1446.
=> Add ability to suppress optimization warnings

changes/1464.feature.md, hikari/api/rest.py, hikari/guilds.py, hikari/internal/routes.py, hikari/stickers.py, tests/hikari/impl/test_rest.py, tests/hikari/test_guilds.py
https://github.com/discord/discord-api-docs/commit/041add9e44fa497795344ffae547b8f0e30a4935
=> Support GIF stickers

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml
For the looks of it, `push` will also be fired on merge groups, which will conflict and cancel the tasks
=> Remove `merge_group` trigger

changes/1516.feature.md, hikari/traits.py
Methods in protocols can be annotated with `abc.abstractmethod` to give better type errors. [PEP 544](https://peps.python.org/pep-0544/#explicitly-declaring-implementation)
In practice (tested with Mypy)
```python
import abc
import typing
class Proto(typing.Protocol):
def function(self) -> None:
raise NotImplementedError
class ProtoAbstract(typing.Protocol):
@abc.abstractmethod
def function(self) -> None:
raise NotImplementedError
class Cls(Proto):
...
Cls()  # this does not give a type error
class Cls2(ProtoAbstract):
...
Cls2()  # this does
```
=> Use abstractmethods for protocols 

changes/1530.doc.md, hikari/api/rest.py, hikari/channels.py, hikari/guilds.py
Minor correction to the documentation for the auto_archive_duration parameter, where it should be in minutes instead of seconds
N/A
=> Correct seconds to minutes in docs for auto_archive_duration

changes/1504.feature.md, hikari/api/rest.py, hikari/api/special_endpoints.py, hikari/interactions/base_interactions.py, hikari/messages.py, hikari/webhooks.py
This PR adds and documents the new [`SUPPRESS_NOTIFICATIONS`](https://github.com/discord/discord-api-docs/commit/dd3f05a1709add398bac3a68af3cc27287f67038) bitwise flag supported on various message response methods.
- Just want to note that flake8 failed due to docstrings (not mine) being written in a way flake8 doesn't like
=> Add suppress_notifications bit flag to MessageFlag

README.md, docs/conf.py, hikari/api/rest.py, pipelines/sphinx.nox.py
This is to aid when it comes to developing the documentations static pages.
Can be done like this:
```
nox -s sphinx -- --no-refs
SKIP_REFERENCE_DOCS=1 nox -s sphinx
```
=> Add flag to skip generation of reference docs when running sphinx

changes/1545.bugfix.md, hikari/internal/ux.py, tests/hikari/internal/test_ux.py
=> Read the banner with `utf-8` encoding

hikari/impl/rate_limits.py, tests/hikari/impl/test_rate_limits.py
=> Improve bucket ratelimiting logging

.github/workflows/fragments-check.yml
This task is so fast that having the concurrency leads to more errors than not
=> Remove fragments check concurrency check

changes/1533.breaking.md, changes/1533.bugfix.md, changes/1533.deprecation.md, changes/1533.feature.md, hikari/api/special_endpoints.py, hikari/impl/special_endpoints.py, tests/hikari/impl/test_rest.py, tests/hikari/impl/test_special_endpoints.py
=> Flatten the component builders

changes/1564.bugfix.md, hikari/api/rest.py, hikari/channels.py, hikari/impl/rest.py, tests/hikari/impl/test_rest.py
Fixed applied forum tags not being a sequence of snowflakes.
=> Fix forum applied tags

pipelines/codespell.nox.py, pipelines/flake8.nox.py, pipelines/format.nox.py, pipelines/mypy.nox.py, pipelines/nox.py, pipelines/pyright.nox.py, pipelines/pytest.nox.py, pipelines/safety.nox.py, pipelines/slotscheck.nox.py
Without this running `nox -s` will lead to flake8 running before reformatting, potentially giving unnecessary black would reformat this errors.
=> Revert changing the default nox -s ordering

changes/1574.feature.md, changes/idk.feature.md, hikari/api/special_endpoints.py, hikari/impl/special_endpoints.py, tests/hikari/impl/test_special_endpoints.py
The primary aim of this is to more consistently provide `set_custom_id`
=> Add more builder set methods

changes/1585.bugfix.md, hikari/impl/config.py
CPython3.11 changes around SSLProto have made this quite unstable and prone to errors when dealing with unclosed TLS transports, which ends up in aiohttp calling close and abort twice.
This has been battle tested by several people on different OS's (both Linux and Windows) and seems to work fine and solve the issues.
=> Default `enable_cleanup_closed` to False

changes/1627.bugfix.md, hikari/impl/rest.py, tests/hikari/impl/test_rest.py
=> Use a stack to keep streams open until usage in `RESTClient.edit_guild`

changes/1648.bugfix.md, hikari/impl/rest.py, tests/hikari/impl/test_rest.py
=> Retry REST requests on connection errors

hikari/embeds.py
Code block was not rendered correctly in current docs (as of 7055102aa2cbeddc8946deccb8de8f83451fe165) ![image](https://github.com/hikari-py/hikari/assets/31789326/9cc050da-d42a-4a8b-b35c-1c1e01f9ef2d) This PR adds it.
None
=> Add code block in `hikari.embeds`'s docs

.github/workflows/fragments-check.yml
This can only be done with a personal access token, which is not something worth having out there publically
=> Remove renaming "idk" changelog files 

changes/1740.feature.md, hikari/api/special_endpoints.py, hikari/impl/special_endpoints.py, tests/hikari/impl/test_special_endpoints.py
=> Add missing clear methods for InteractionMessageBuilder

README.md
Updating the deprecated uvloop.install() call.
=> Remove deprecated uvloop method usage

tests/hikari/impl/test_rate_limits.py
This has been causing warnings (and, by extension, errors) occasionally when running pytest, more specifically when these tests are the first to run and no event loop exists
=> Ensure we have a loop when running ratelimit tests

changes/1828.feature.md, hikari/api/rest.py, hikari/guilds.py, hikari/impl/rest.py, tests/hikari/impl/test_rest.py, tests/hikari/test_guilds.py
This PR adds two missing mutable guild features to `GuildFeature` enums, introduces `MutableGuildFeature` for ease of use, and a `features` argument to `edit_guild()` to address the lack of support for editing guild features. Relevant docstrings and tests had been updated accordingly.
Resolves #1768.
Partially addresses #1827.
=> Allow changing guild features (community, etc.)

hikari/api/entity_factory.py, hikari/api/event_factory.py, hikari/api/interaction_server.py, hikari/api/rest.py, hikari/api/shard.py, hikari/api/special_endpoints.py, hikari/channels.py, hikari/commands.py, hikari/embeds.py, hikari/guilds.py, hikari/impl/event_manager_base.py, hikari/impl/gateway_bot.py, hikari/impl/interaction_server.py, hikari/impl/rest.py, hikari/impl/rest_bot.py, hikari/impl/shard.py, hikari/impl/special_endpoints.py, hikari/interactions/base_interactions.py, hikari/internal/collections.py, hikari/internal/data_binding.py, hikari/internal/deprecation.py, hikari/messages.py, hikari/templates.py, hikari/traits.py, hikari/users.py, hikari/webhooks.py
This distinction no-longer serves a purpose and prevents field defaults from being show in the parameters table.
In the old doc gen system this distinction was done as a way to document fields as being optional since the parameter defaults weren't actually included in the generated docs. But mkdocstrings-python includes them so this is now redundant and prob even a bit confusing (since it doesn't actually distinguish between the two different tqables).
=> Merge the Parameters and Other Parameters doc sections

changes/1943.feature.md, hikari/impl/event_manager_base.py, hikari/impl/interaction_server.py, tests/hikari/impl/test_event_manager_base.py, tests/hikari/impl/test_interaction_server.py
Add payload to deserialization error to make it easier to diagnose
None
=> Add payload to deserialization error to make it easier to diagnose

hikari/events/lifetime_events.py
Corrected the docstrings for StartingEvent and StoppingEvent, both of which suggest the use of themselves over StartedEvent and StoppedEvent respectively.
None
=> Fix docstring typos pointing to incorrect events

.gitignore, changes/2059.bugfix.md, hikari/impl/interaction_server.py
In aiohttp 3.10.6, a new abstract method was added to `aiohttp.Payload`, so trying to instantiate our `_FilePayload`, would cause issues.
It is impossible to implement `.decode` in a sync context, so, for now, just error pointing them to raise an issue with us if this ever becomes an issue in the future, in which case we will have to revisit this and look for an alternative and better solution
=> Fix uploading files when using aiohttp 3.10.6 and onwards

changes/2066.feature.md, hikari/api/rest.py, hikari/impl/rest.py, tests/hikari/impl/test_rest.py
Allow specifying a reason for message deletions.
Has some caveats, namely:
- Audit log entries merging seems to erase the reason at times. 
- Bulk delete reason doesn't seem to work fully from Discord's end, however their docs do say it's supported.
None
=> Allow specifying a reason for message deletions

changes/2149.bugfix.md, hikari/impl/entity_factory.py, tests/hikari/impl/test_entity_factory.py
Entitlement `starts_at` and `ends_at` are nullable in the Discord API, and if it's null, results in this error:
```
ends_at=time.iso8601_datetime_string_to_datetime(payload["ends_at"]) if "ends_at" in payload else None,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/python3.12/site-packages/hikari/internal/time.py", line 81, in slow_iso8601_datetime_string_to_datetime
if datetime_str.endswith(("z", "Z")):
^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'endswith'
```
The error for `starts_at` is similar.
=> Fix entitlement starts_at and ends_at erroring when null

uv.lock
https://github.com/advisories/GHSA-cpwx-vrp4-4pq7
=> Lock jinja2 to >=3.1.6

.github/workflows/ci.yml, pipelines/pytest.nox.py
Coverage can now be enabled by providing `--coverage` as an argument like so: `nox -s pytest -- --coverage`
=> Do not run pytest with coverage by default

CONTRIBUTING.md, README.md
In the contributing guide was a small mistake for installing nox.
I know that the `--group` was already merged into master but it isn't released yet and that is prob. a bit confusing for beginners.
Also you needed to install uv using pip `pip install uv` for nox to work properly. Ofc this is something that a lot of people who want to contribute would figure out in a second but idk I feel like it could still be fixed.
=> Use uv as package manager in the contribution guide

pyproject.toml
the old state of this isn't accurate, it's misleading/wrong to say someone who isn't associated with the project is an author
=> Remove FasterSpeeding from authors section

changes/2280.feature.md, hikari/api/interaction_server.py, hikari/impl/interaction_server.py, tests/hikari/impl/test_interaction_server.py
This PR allows REST interaction handlers to return None instead of a response builder - indicating that the interaction was responded to manually using an HTTP request. [Relevant documentation](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-callback)
=> feat: no-content responses when interaction handlers return None

hikari/api/rest.py, hikari/impl/rest.py, tests/hikari/impl/test_rest.py
Fix `end_poll` method in `RESTClient` to return a message object instead of `None`.
=> Fix `end_poll` method in `RESTClient`.

pipelines/nox.py
This should avoid errors where adding or updating new dependencies will silently not install them, leading to confusion
=> Use `--locked` instead of `--frozen` when syncing nox pipelines

changes/2303.bugfix.md, hikari/applications.py, hikari/impl/entity_factory.py, tests/hikari/impl/test_entity_factory.py
The [Discord documentation for the Application object](https://discord.com/developers/docs/resources/application#application-object-application-structure) specifies an optional ``approximate_user_install_count`` field.
Also, I noticed that the ``approximate_guild_count`` field is optional in Discord's specification, but is required for the Application class.
This pull request:
- Adds the ``approximate_user_install_count`` attribute to the ``hikari.Application`` class.
- Modifies the ``hikari.Application.approximate_guild_count`` attribute type hint to reflect the Discord documentation (can be None).
- Modifies the ``deserialize_application`` function to read fields ``approximate_user_install_count`` and ``approximate_guild_count`` as optional.
- Modifies test_entity_factory to include the …
=> Add approximate_user_install_count attribute to hikari.Application

tests/hikari/impl/test_rest.py
Added the missing tests for the code that automatically adds the `IS_COMPONENTS_V2` flag to a message payload if the user adds a V2 component.
=> Add missing tests for components V2

uv.lock
Addresses h11 osv.dev/vulnerability/GHSA-vqfr-h8mv-ghfj
=> Bump httpcore lock to 1.0.9

hikari/impl/special_endpoints.py, tests/hikari/impl/test_special_endpoints.py
This should improve typecheckers ability to infer the types properly
This has no user impact
=> Set button builder specifics in the sub-builders

changes/2355.bugfix.md, hikari/api/rest.py
Added missing docstrings for voice messages in the rest API. Updated the waveform description for voice messages.
fix/missing-voice-message-docstrings
=> Add missing voice message docstrings

changes/2368.optimization.md, hikari/api/event_manager.py, hikari/impl/event_manager.py, hikari/impl/event_manager_base.py, hikari/impl/gateway_bot.py, hikari/impl/shard.py, tests/hikari/impl/test_event_manager.py, tests/hikari/impl/test_event_manager_base.py, tests/hikari/impl/test_gateway_bot.py
Instead of creating tasks that keep references to soon to be deleted objects (ie, payloads) we can optimize the lifetime of each of these objects and have them be marked for removal by the GC as soon as possible
=> Greatly optimize event manager memory management

changes/2395.feature.md, hikari/impl/config.py, hikari/impl/shard.py, hikari/internal/net.py, hikari/internal/ux.py, tests/hikari/impl/test_shard.py, tests/hikari/internal/test_ux.py
This allows increasing the limit for large shard clusters, where there will be a lot of continuous requests being made, provided that the underlying architecture can handle it
=> Allow setting HTTP concurrent connection limit

changes/2403.optimization.md, hikari/impl/buckets.py, tests/hikari/impl/test_buckets.py
=> Revert "Only lock buckets to a single request if they are unknown"

changes/2434.bugfix.md, hikari/internal/enums.py
=> Fix enum `__getitem__` not properly returning items with a falsy value
