hikari-py/hikari

hikari/utilities/iterators.py

Implement "chunk" method for lazy iterator and add __iter__ override for more helpful error message.
* Fix LazyIterator.last returning the first entry of the last page instead of the first.
* Rename LazyIterator.first to "next".
* Cleanup some doc references to type hints within iterators.py

Implement "chunk" method for lazy iterator and add __iter__ override for more helpful error message.

---

hikari/impl/bot.py
hikari/impl/shard.py
hikari/utilities/version_sniffer.py
tests/hikari/impl/test_shard.py
tests/hikari/utilities/test_version_sniffer.py

- Fixed regression preventing status updates.
- Fixed erraneous "update hikari" message on non-PyPI versions.
- Updated presence field types.

WIP: various gateway bugfixes and runtime bugfixes

---

.github/ISSUE_TEMPLATE/feature_request.md
hikari/__init__.py
hikari/models/webhooks.py
hikari/traits.py
tests/hikari/models/test_users.py

- Fixed broken docstrings
- Fix black and isort fighting eachother

Added tests for Users

---

.github/auto-merge.yml

This will allow any PR with an `automerge` label to be automatically merged once at least one approval has been given.

Added an automerge configuration.

---

hikari/utilities/art.py

Added clicolors support (environment variables only currently)
https://bixense.com/clicolors/

Added CLICOLOR and CLICOLOR_FORCE environment variable support.

---

hikari/__init__.py
hikari/impl/bot.py
hikari/traits.py

Added missing import to `__init__.py`

---

pages/index.html

He is a special person with a special browser.

Fixed broken HTML on Thommo's machine

---

mypy-requirements.txt
pipelines/development.nox.py

Install into the generated venv's pip instead of nox's env pip in init task
- [ x] I have run `nox` and all the pipelines have passed.

Install into the generated venv's pip instead of nox's env pip in init task

---

.travis.yml

Fixing stackless container to die properly.

---

hikari/impl/bot.py

@FasterSpeeding please verify this handles keyboard interrupts and invoking `bot.close()`/`sys.exit` within commands on Windows.

Reimplemented BotApp.run to have more concrete signal handling and to tidy up resources.

---

hikari/utilities/constants.py

Whatever, if it will make people leave me alone for a while :)

Fixed a character that seems to have been emotionally distressing people

---

hikari/api/cache.py
hikari/events/channel_events.py
hikari/events/guild_events.py
hikari/events/member_events.py
hikari/events/message_events.py
tests/hikari/events/test_channel_events.py
tests/hikari/hikari_test_helpers.py

Event utility methods and stuff.

Draft: Feature/event methods

---

hikari/impl/event_manager_base.py
hikari/utilities/date.py
hikari/utilities/reflect.py
requirements.txt
tests/hikari/impl/test_event_manager_base.py

Reduced average time parsing ISO-8601 timestamps in presences from 4.5µs to 190ns on x86 by adding a compiled module.

Optimisations to datetime parsing.

---

dev-requirements.txt
flake8-requirements.txt
pipelines/development.nox.py
pipelines/format.nox.py
pipelines/pytest.nox.py
pipelines/safety.nox.py
pipelines/twemoji.nox.py
requirements.txt

Thanks to us having @dependabot we can safely freeze requirements allowing us to make sure that the specific package will work on the specific version. This also makes pipelines run the same version of the extensions on all computers

Freeze requirements and add update flag to pipelines

---

hikari/api/rest.py

Add REST documentation
Relates to #42

Add REST documentation

---

hikari/api/chunker.py
hikari/api/event_dispatcher.py
hikari/api/rest.py
hikari/channels.py
hikari/events/shard_events.py
hikari/files.py
hikari/impl/bot.py
hikari/impl/shard.py
hikari/impl/stateful_guild_chunker.py
hikari/iterators.py
hikari/messages.py
hikari/utilities/cache.py
hikari/utilities/data_binding.py
hikari/utilities/event_stream.py
hikari/webhooks.py

Documentation consistency fixes

---

docs/documentation.mako
hikari/impl/buckets.py

Added pdoc helper to find reference errors

Added pdoc helper to find reference errors

---

hikari/api/shard.py
hikari/impl/bot.py
hikari/impl/shard.py
hikari/utilities/aio.py

- Fixed some other bugs I found

Proper shutting down

---

hikari/events/guild_events.py

Add missing "GuildEvent" to guild_events.__all__
- [x ] I have made unittests according to the code I have added/modified/deleted.

Add missing "GuildEvent" to guild_events.__all__

---

hikari/users.py
tests/hikari/impl/test_entity_factory.py

Updated some user flag naming.

Renamed some user flags.

---

hikari/api/rest.py
hikari/impl/bot.py
hikari/impl/rest.py
hikari/impl/shard.py

- Fix some typehints in REST
- Fix logging message in bot
- If we are expecting a BINARY, but get something different, we now error out

Several bug fixes

---

hikari/impl/bot.py

Fix being unable to shut down bot

---

hikari/api/entity_factory.py
hikari/impl/bot.py
hikari/traits.py

Add `update_presence` to bot

---

hikari/banner.txt
hikari/impl/bot.py
hikari/impl/rest.py
hikari/impl/shard.py
tests/hikari/impl/test_rest.py
tests/hikari/impl/test_shard.py

- This should hopefully fix WinError 10038 that gets raised sometimes on Windows

Dont force to close TCP connectors

---

hikari/impl/bot.py
hikari/traits.py

Add methods around starting and stopping the bot app to the BotAware trait and move docs from impl
- [ x] I have run `nox` and all the pipelines have passed.
- [x ] I have made unittests according to the code I have added/modified/deleted.

Add methods to BotAware along with moving docs

---

hikari/api/cache.py
hikari/api/entity_factory.py
hikari/api/rest.py
hikari/channels.py
hikari/events/channel_events.py
hikari/events/message_events.py
hikari/events/typing_events.py
hikari/impl/entity_factory.py
hikari/impl/rest.py
hikari/impl/stateful_cache.py
hikari/impl/stateful_event_manager.py
hikari/impl/stateless_cache.py
hikari/intents.py
hikari/utilities/cache.py
tests/hikari/impl/test_entity_factory.py
tests/hikari/impl/test_rest.py
tests/hikari/impl/test_stateful_cache.py
tests/hikari/impl/test_stateless_cache.py
tests/hikari/test_channels.py

Rename private text channels to DMs

---

hikari/api/cache.py
hikari/events/channel_events.py
hikari/events/guild_events.py
hikari/events/member_events.py
hikari/events/message_events.py
hikari/events/typing_events.py
hikari/guilds.py
hikari/impl/entity_factory.py
hikari/impl/rest.py
hikari/impl/stateful_cache.py
hikari/impl/stateful_event_manager.py
hikari/impl/stateless_cache.py
hikari/presences.py
hikari/utilities/attr_extensions.py
hikari/utilities/cache.py
hikari/utilities/mapping.py
hikari/webhooks.py
tests/hikari/events/test_channel_events.py
tests/hikari/events/test_guild_events.py
tests/hikari/events/test_member_events.py
tests/hikari/events/test_message_events.py
tests/hikari/events/test_typing_events.py
tests/hikari/impl/test_entity_factory.py
tests/hikari/impl/test_stateful_cache.py
tests/hikari/impl/test_stateless_cache.py

* Remove the UnavailableGuild model
* Separate guild reading methods for guild into available and unavailable guild methods (with these changes reflected in model methods).

Remove the UnavailableGuild model and separate available and unavailable guilds in the cache

---

docs/documentation.mako
hikari/api/rest.py

New rest docs

---

hikari/impl/rest.py
tests/hikari/impl/test_rest.py

Remove ability to set REST version

---

CONTRIBUTING.md

Fix CONTRIBUTING.md to remove references to dead branches

---

hikari/guilds.py

Document new RELAY_ENABLED guild feature.
Links to https://github.com/discord/discord-api-docs/pull/2038

Document RELAY_ENABLED guild feature for large guilds.

---

hikari/errors.py

Remove unused Unavailable guild error

---

hikari/guilds.py
hikari/impl/entity_factory.py
hikari/utilities/cache.py
tests/hikari/impl/test_entity_factory.py

Will be documented by https://github.com/discord/discord-api-docs/pull/2044 as soon as it is merged.
Until then, marking this as pending.

Make Member#premium_since mandatory.

---

hikari/__init__.py

Added colors back to import path.

---

hikari/files.py

Added the ability to mark files as spoilers

---

hikari/guilds.py
tests/hikari/test_guilds.py

Add `top_role` property to member

---

hikari/utilities/aio.py

Fix mypy error

---

hikari/api/chunker.py
hikari/impl/stateful_guild_chunker.py

Make "limit" default to None on GuildCHunker.fetch_members_for_guild

---

hikari/impl/bot.py

Optimize `shards` property

---

hikari/impl/bot.py

Add ability to disable checking for updates

---

hikari/impl/shard.py

Fix incorrect encoding being sent

---

speedup-requirements.txt

Using PEP 508 dependency specifiers.

Added uvloop provisionally to linux only systems

---

docs/documentation.mako

Fix attribute linking in properties

---

hikari/api/rest.py
hikari/errors.py
hikari/impl/rest.py
hikari/impl/special_endpoints.py
tests/hikari/impl/test_rest.py

- Fix x_emoji typehints
Closes #42

Added all missing docs on REST

---

hikari/errors.py
hikari/utilities/net.py
tests/hikari/test_errors.py
tests/hikari/utilities/test_net.py

Improve error str and added code + message

---

hikari/errors.py
hikari/utilities/net.py

Added RESTErrorCode

---

hikari/api/shard.py
hikari/impl/bot.py
hikari/impl/shard.py
hikari/impl/stateful_guild_chunker.py
hikari/traits.py
tests/hikari/impl/test_shard.py
tests/hikari/impl/test_stateful_guild_chunker.py

Disable intents from being None

---

hikari/utilities/ux.py

Tmpod said he would beat me if I didn't add this, and that man has a very hard hand, from experience.

Added support for color detection via COLORTERM env var.

---

.gitignore
hikari/config.py
hikari/impl/bot.py
hikari/presences.py
hikari/utilities/ux.py

This makes some warnings appear if you send deprecated or badly formatted presence updates.
Should stop people asking "why does this not work" :)

Added warnings for bad presence update payloads.

---

hikari/guilds.py

Addresses #231 by adding a `presence` property to the `Member` object.

Fixes #231 - adds Member.presence property.

---

hikari/api/chunker.py
hikari/api/entity_factory.py
hikari/api/rest.py
hikari/api/shard.py
hikari/api/special_endpoints.py
hikari/channels.py
hikari/embeds.py
hikari/events/guild_events.py
hikari/events/message_events.py
hikari/events/shard_events.py
hikari/files.py
hikari/impl/bot.py
hikari/impl/special_endpoints.py
hikari/messages.py
hikari/traits.py
hikari/utilities/cache.py
hikari/utilities/data_binding.py
hikari/webhooks.py

Moved optinal arguments to `Other Parameters` sublist

---

.flake8
hikari/api/rest.py
hikari/api/special_endpoints.py
hikari/files.py
hikari/impl/bot.py
hikari/impl/buckets.py
hikari/impl/entity_factory.py
hikari/impl/event_factory.py
hikari/impl/rate_limits.py
hikari/impl/rest.py
hikari/impl/shard.py
hikari/impl/special_endpoints.py
hikari/impl/stateful_guild_chunker.py
hikari/sessions.py
hikari/snowflakes.py
hikari/utilities/net.py
hikari/utilities/time.py
tests/hikari/impl/test_buckets.py
tests/hikari/impl/test_shard.py
tests/hikari/utilities/test_time.py

Rename `hikari.utitlities.date` to `hikari.utilities.time`

---

hikari/files.py
hikari/impl/bot.py
hikari/impl/buckets.py
hikari/impl/rest.py
hikari/impl/shard.py
hikari/impl/special_endpoints.py
hikari/impl/stateful_guild_chunker.py
tests/hikari/impl/test_buckets.py
tests/hikari/impl/test_shard.py
tests/hikari/impl/test_stateful_guild_chunker.py

I messed up and forgot to stage this on #239 :sweat_smile: 
None

Fix a unbound error

---

docs/documentation.mako
hikari/config.py
hikari/impl/bot.py
hikari/utilities/collections.py

Fix documentation issues

---

hikari/api/chunker.py
hikari/impl/event_manager_base.py
hikari/impl/shard.py

Fix some inconsistencies across the library

---

hikari/intents.py

Fix DM_MESSAGES documentation to remove CHANNEL_CREATE

---

hikari/__init__.py
hikari/api/chunker.py
hikari/api/entity_factory.py
hikari/api/event_dispatcher.py
hikari/api/event_factory.py
hikari/api/rest.py
hikari/config.py
hikari/impl/buckets.py
hikari/impl/shard.py
hikari/internal/cache.py

Fix documentation references

---

hikari/impl/rest.py

Fix AttributeError on create_role

---

hikari/permissions.py

Rename `USE_VAD` to `USE_VOICE_ACTIVITY` to reduce confusion

---

hikari/impl/entity_factory.py
tests/hikari/impl/test_entity_factory.py

Add guild ID to Member.role_ids to cover the @everyone role

Add guild ID to Member.role_ids to cover the @everyone role

---

hikari/impl/bot.py

suppress a uvloop specific not implemented error

suppress a uvloop specific not implemented error

---

hikari/impl/bot.py

Fix shutting down default executor several times

---

examples/__init__.py
examples/hello_world/__init__.py
examples/hello_world/hello_world.py
examples/hello_world/hello_world.sh
examples/image_resources/__init__.py
examples/image_resources/image_resources.py
examples/image_resources/image_resources.sh
hikari/files.py
pipelines/flake8.nox.py
pipelines/format.nox.py
pipelines/mypy.nox.py
scripts/deploy.sh

Make flake8 and mypy run on examples

---

hikari/applications.py
hikari/audit_logs.py
hikari/channels.py
hikari/errors.py
hikari/guilds.py
hikari/invites.py
hikari/messages.py
hikari/presences.py
hikari/users.py
hikari/webhooks.py

Remove duplicate `__str__` code on enums

---

hikari/__init__.py
hikari/snowflakes.py
pages/index.html

- Remove random function from root of package
- Remove "Reports for this build" from main page
- Fix typehint in snowflakes.py

General tidyups

---

.travis.yml
pipelines/docker/stackless-3.8.0b3/Dockerfile

Moves stackless python docker container building task to master.
I've set up a weekly cron job to rebuild these now, additionally, if I make a commit on master with `[rebuild containers]` in the content, this should also manually trigger a rebuild.

Moved CI container scripts to master [rebuild containers]

---

hikari/internal/aio.py
hikari/internal/time.py
pipelines/pytest.nox.py
tests/hikari/events/test_message_events.py
tests/hikari/impl/test_entity_factory.py
tests/hikari/internal/test_collections.py
tests/hikari/internal/test_ux.py
tests/hikari/test_colors.py
tests/hikari/test_errors.py
tests/hikari/test_event_stream.py
tests/hikari/test_users.py

And more testing

---

hikari/api/rest.py
tests/hikari/impl/test_buckets.py
tests/hikari/impl/test_rest.py

Fix documentation and tests

---

.travis.yml

Fix uploading code coverage to codeclimate

---

.travis.yml
scripts/test-job.sh

Fix travis CI issues

---

dev-requirements.txt
hikari/impl/rest.py

Bump mypy from 0.782 to 0.790

---

hikari/internal/collections.py

Update docstring of `collections.copy_mapping`

---

hikari/undefined.py
hikari/undefined.pyi

Fix not documenting UNDEFINED properly

---

docs/config.mako
docs/head.mako
pages/index.html

Fix links in pages

---

hikari/errors.py
hikari/impl/buckets.py

- Improved logic and RateLimitTooLongError error message

Fix max_rate_limit

---

docs/patched_pdoc.py

Remove hyperlinks pointing to `index.html` in search
Fixes #296

Dont document index.html in the index

---

hikari/errors.py
hikari/guilds.py

New JSON Codes and remove `PUBLIC` and `PUBLIC_DISABLED` flags

---

pipelines/format.nox.py
scripts/deploy-manually.sh
scripts/deploy-pages.sh
scripts/deploy.sh
scripts/deploy_webhook.py
scripts/test-job.sh

Add missing copyright

---

hikari/api/entity_factory.py
hikari/api/event_factory.py
hikari/applications.py
hikari/events/guild_events.py
hikari/guilds.py
hikari/impl/entity_factory.py
hikari/impl/event_factory.py
hikari/impl/event_manager_base.py
hikari/impl/rest.py
hikari/impl/stateful_event_manager.py
hikari/impl/stateless_event_manager.py
hikari/intents.py
hikari/messages.py
tests/hikari/impl/test_entity_factory.py
tests/hikari/impl/test_event_manager_base.py
tests/hikari/impl/test_rest.py
tests/hikari/impl/test_stateless_event_manager.py
tests/hikari/test_applications.py
tests/hikari/test_guilds.py

Add new integration events to replace guild integrations update

Add new integration events

---

hikari/guilds.py
tests/hikari/impl/test_entity_factory.py
tests/hikari/internal/test_enums.py
tests/hikari/test_messages.py

More testing

---

hikari/impl/bot.py
hikari/impl/entity_factory.py
hikari/internal/collections.py
hikari/messages.py
tests/hikari/impl/test_entity_factory.py
tests/hikari/test_messages.py

New mention object and small cleanups

---

hikari/impl/bot.py
hikari/impl/buckets.py
hikari/impl/rest.py
hikari/impl/shard.py
tests/hikari/impl/test_buckets.py
tests/hikari/impl/test_rest.py
tests/hikari/impl/test_shard.py

Implement a lock to help ratelimiting handling

---

hikari/api/rest.py
hikari/impl/rest.py
hikari/internal/routes.py
tests/hikari/impl/test_rest.py

Add logic and abstact method for search members endpoint

---

pipelines/pytest.nox.py
pipelines/utils.nox.py

- Added `node_modules` and `package-lock.json` to purged

Fix removing files on pipelines

---

hikari/api/rest.py
hikari/impl/rest.py
tests/hikari/impl/test_rest.py

Rename `create_crossposts` to `crosspost_message`

---

hikari/api/rest.py

Add intent warning to `fetch_members`

---

hikari/api/rest.py
hikari/impl/rest.py
hikari/internal/routes.py
hikari/webhooks.py
tests/hikari/test_webhooks.py

New webhook endpoints

---

hikari/api/chunker.py
hikari/api/rest.py
hikari/api/shard.py
hikari/channels.py
hikari/errors.py
hikari/impl/rest.py
hikari/impl/shard.py
hikari/impl/stateful_guild_chunker.py
hikari/impl/stateless_guild_chunker.py
hikari/messages.py
hikari/snowflakes.py
hikari/webhooks.py

Refactor ID sequences into Snowflakes

---

docs/documentation.mako
hikari/api/event_dispatcher.py
hikari/api/rest.py
hikari/applications.py
hikari/events/lifetime_events.py
hikari/internal/data_binding.py
hikari/messages.py

Fix documentation linking

---

hikari/config.py
hikari/impl/bot.py
hikari/impl/stateful_cache.py
tests/hikari/impl/test_stateful_cache.py

Moved cache configuration to own class

---

hikari/embeds.py
hikari/impl/bot.py
hikari/internal/ux.py

Fix logging

---

hikari/impl/event_manager_base.py

Fix bug on wait_for so that timeouts remove it from the waiters_set

---

hikari/guilds.py
hikari/users.py
tests/hikari/test_guilds.py
tests/hikari/test_users.py

Implement user DM flow

---

hikari/api/cache.py

Move message cache methods to cache rather than mutable cache

---

hikari/__init__.py
hikari/api/entity_factory.py
hikari/api/rest.py
hikari/applications.py
hikari/guilds.py
hikari/impl/entity_factory.py
hikari/impl/rest.py
hikari/internal/routes.py
hikari/invites.py
hikari/templates.py
tests/hikari/impl/test_entity_factory.py
tests/hikari/impl/test_rest.py
tests/hikari/test_guilds.py

Add endpoints and objects for handling templates.

Add endpoints and objects for handling templates.

---

hikari/impl/entity_factory.py
hikari/webhooks.py
tests/hikari/impl/test_entity_factory.py
tests/hikari/test_webhooks.py

Add source_guild and source_channel to Webhook

Add source_guild and source_channel to Webhook

---

hikari/guilds.py
hikari/impl/entity_factory.py
hikari/internal/cache.py
hikari/internal/data_binding.py
tests/hikari/impl/test_entity_factory.py
tests/hikari/impl/test_stateful_cache.py
tests/hikari/integration/test_users_comparison.py
tests/hikari/test_guilds.py

Document Member.is_pending and the associated guild feature

---

hikari/api/cache.py
hikari/guilds.py
tests/hikari/test_guilds.py

Add missing Member.roles property

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml

Link to discussions in issue form

---

hikari/api/rest.py
hikari/cli.py
hikari/events/guild_events.py
hikari/impl/event_manager.py
hikari/internal/ux.py
pipelines/pages.nox.py
tests/hikari/impl/test_event_manager.py

- Fix outputing sha1 and version in cli
- Fix outputing version in pypi version detection
- Rename `GuildAvailableEvent.guild_chunk_nocne` to `GuildAvailableEvent.chunk_nonce`

Fix pypi version detection and rename some attributes

---

hikari/impl/event_manager.py
tests/hikari/impl/test_event_manager.py

ignore redundant ON_GUILD_INTEGRATIONS_UPDATE gateway event

---

hikari/api/event_dispatcher.py
hikari/api/event_factory.py
hikari/api/event_manager.py
hikari/event_stream.py
hikari/impl/bot.py
hikari/impl/event_factory.py
hikari/impl/event_manager.py
hikari/impl/event_manager_base.py
hikari/impl/shard.py
hikari/impl/voice.py
hikari/traits.py
hikari/webhooks.py
tests/hikari/impl/test_event_manager.py
tests/hikari/impl/test_event_manager_base.py
tests/hikari/impl/test_shard.py
tests/hikari/test_event_stream.py

Proof of concept around allowing for raw listeners

Rename EventDispatcher to EventManager and add a public raw event consumer system

---

hikari/api/event_factory.py

Make hikari.api.event_factory.EventFactory an abstract class

Make hikari.api.event_factory.EventFactory an abstract class

---

.github/workflows/ci.yml
docs/body.mako
docs/config.mako
docs/css.mako
docs/documentation.mako
docs/footer.mako
docs/head.mako
docs/html.mako
docs/patched_pdoc.py
docs/search.mako
hikari/api/cache.py
hikari/api/voice.py
pages/index.html
pipelines/pages.nox.py
scripts/prebuild_index.js

Improve search and cleanup docs

---

hikari/undefined.pyi
pyproject.toml

Change black's include pattern to include .pyi files

---

.github/workflows/ci.yml

Enable python 3.10 ci

---

hikari/api/entity_factory.py
hikari/api/rest.py
hikari/guilds.py
hikari/impl/entity_factory.py
hikari/impl/rest.py
hikari/internal/routes.py
hikari/invites.py
tests/hikari/impl/test_entity_factory.py
tests/hikari/impl/test_rest.py

Add the welcome channel related models and REST endpoints #440
Close #420

Add the welcome channel related models and REST endpoints

---

hikari/impl/entity_factory.py
hikari/internal/cache.py
hikari/messages.py
tests/hikari/impl/test_cache.py
tests/hikari/impl/test_entity_factory.py
tests/hikari/test_messages.py

Implement Sticker model
Close #351

Implement Sticker model

---

README.md
hikari/api/event_manager.py
hikari/event_stream.py
hikari/impl/bot.py
hikari/impl/event_manager.py
hikari/impl/event_manager_base.py
hikari/impl/rest.py
hikari/impl/shard.py
hikari/impl/voice.py
hikari/internal/protocol.py
hikari/internal/protocol.pyi
hikari/traits.py
pages/index.html
scripts/protocol_benchmark.py
tests/hikari/impl/test_event_manager_base.py
tests/hikari/impl/test_shard.py
tests/hikari/internal/test_protocol.py
tests/hikari/test_event_stream.py

- Remove unused args from slots
- Cleanup code
- Remove unused variables
- Fix documentation links
```
isinstance(long, BasicPyProtocol) 10.502764225999272 µs
isinstance(long, BasicHikariProtocol) 0.8962424719993578 µs
isinstance(failfast, BasicPyProtocol) 19.83291287300017 µs
isinstance(failfast, BasicHikariProtocol) 0.3696172330000991 µs
issubclass(long, BasicPyProtocol) 0.3248153929998807 µs
issubclass(long, BasicHikariProtocol) 0.30592563200116274 µs
issubclass(failfast, BasicPyProtocol) 0.3142782159993658 µs
issubclass(failfast, BasicHikariProtocol) 0.29908469400106696 µs
```

Revert raw event consumer system and traits optimization

---

dev-requirements.txt
hikari/config.py
hikari/impl/cache.py
hikari/impl/entity_factory.py
hikari/impl/rest.py
hikari/internal/cache.py

Bump mypy to 0.800 and fix issues

---

hikari/api/entity_factory.py
hikari/api/rest.py
hikari/guilds.py
hikari/impl/entity_factory.py
hikari/impl/event_manager_base.py
hikari/impl/rest.py
hikari/internal/routes.py
tests/hikari/impl/test_entity_factory.py
tests/hikari/impl/test_rest.py

Add entities and rest endpoints for guild member screening
Closes #409

Add entities and rest endpoints for guild member screening

---

hikari/api/rest.py
hikari/events/base_events.py
hikari/impl/entity_factory.py
hikari/impl/event_factory.py
hikari/impl/rest.py
hikari/impl/special_endpoints.py
hikari/messages.py
tests/hikari/impl/test_rest.py

Replace typing.cast with assert statement where possible
* Plus remove some unnecessary casts
* Add object returns to relevant delete endpoints.
* Fix some missing test parts for the rest client

Replace typing.cast with assert statement where possible

---

hikari/api/entity_factory.py
hikari/api/rest.py
hikari/applications.py
hikari/guilds.py
hikari/impl/bot.py
hikari/impl/entity_factory.py
hikari/impl/rest.py
hikari/internal/routes.py
hikari/traits.py
tests/hikari/impl/test_entity_factory.py
tests/hikari/impl/test_rest.py

Implement the fetch authorization information rest endpoint and model

Implement the fetch authorization information rest endpoint and model

---

.github/workflows/ci.yml
CONTRIBUTING.md
README.md

- Add test installation job to pipeline

Fix some issues in the documentation

---

hikari/cli.py

Add helpful sha1 on SNAPSHOT versions

---

hikari/api/cache.py
tests/hikari/test_audit_logs.py

Even more testing

---

hikari/messages.py

Add the new message types

---

hikari/applications.py

Add slash command related oauth2 scopes.

Add slash command related oauth2 scopes.

---

hikari/traits.py

Add close method to the BotAware trait

Add close method to the BotAware trait

---

hikari/permissions.py

Add the use application commands permission

Add the use application commands permission

---

hikari/api/rest.py
hikari/audit_logs.py
hikari/channels.py
hikari/events/channel_events.py
hikari/events/typing_events.py
hikari/guilds.py
hikari/messages.py
hikari/users.py
hikari/webhooks.py
tests/hikari/test_guilds.py

Add missing documentation

---

hikari/api/cache.py
hikari/applications.py
hikari/internal/enums.py
hikari/webhooks.py
tests/hikari/hikari_test_helpers.py

Fixed some todos

---

docs/documentation.mako

Prevent linking to `about`

---

hikari/api/voice.py

Remove debug from the VoiceConnection abc

---

hikari/emojis.py

**IMPORTANT**
There will be no releases till this is fixed. This is only a temporary measure to be able to continue working on the lib

Temporarily remove emoji validation and unicode_names

---

docs/documentation.mako
hikari/events/base_events.py
hikari/internal/deprecation.py
hikari/internal/net.py
hikari/internal/ux.py
tests/hikari/impl/test_rest.py
tests/hikari/impl/test_shard.py
tests/hikari/internal/test_deprecation.py

Deprecation utils

---

scripts/test_twemoji_mapping.py

Switch to minified map in twemoji pipeline

Switch to minified map in twemoji pipeline

---

hikari/applications.py
hikari/events/shard_events.py
hikari/impl/event_factory.py

Add application flags and ID to the ready event.

Add application flags and ID to the ready event.

---

hikari/applications.py
hikari/impl/entity_factory.py
tests/hikari/impl/test_entity_factory.py

Add application tos and privacy policy urls

Add application tos and privacy policy urls

---

hikari/api/rest.py
hikari/audit_logs.py
hikari/impl/rest.py
hikari/impl/special_endpoints.py
hikari/internal/data_binding.py

Fix specifying action_type in fetch_audit_log

---

hikari/guilds.py

Add new Suppress Guild Reminder flag

---

hikari/applications.py

Remove RPC_API

---

hikari/messages.py

Document missing message types

---

hikari/messages.py

Add new "EPHEMERAL" and "LOADING" message types

---

hikari/impl/entity_factory.py
hikari/messages.py
tests/hikari/impl/test_entity_factory.py
tests/hikari/test_messages.py

Document Attachment content type

---

hikari/impl/entity_factory.py
hikari/presences.py
tests/hikari/impl/test_entity_factory.py

"region" was renamed to "rtc_region" and made nullable in payloads; remove warning from WATCHING

---

hikari/events/voice_events.py
hikari/impl/voice.py
tests/hikari/events/test_voice_events.py

Document "raw_endpoint" and "endpoint" as being nullable

---

hikari/api/rest.py

Add intent requirement to only be enabled in dashboard

---

hikari/api/rest.py
hikari/messages.py
hikari/webhooks.py

Document the re-parsing of allowed_mentions on non-embed content

---

hikari/errors.py

Document unknown guild template error code

---

hikari/applications.py
hikari/channels.py
hikari/guilds.py
hikari/invites.py
hikari/messages.py
hikari/users.py
hikari/webhooks.py
tests/hikari/test_applications.py
tests/hikari/test_channels.py
tests/hikari/test_guilds.py
tests/hikari/test_messages.py
tests/hikari/test_users.py

Rename `format_x` to `make_x_url`

---

hikari/api/rest.py
hikari/impl/rest.py
hikari/internal/routes.py
hikari/webhooks.py
tests/hikari/impl/test_rest.py
tests/hikari/test_webhooks.py

Implement new fetch_webhook_message

---

hikari/api/shard.py
hikari/events/channel_events.py
hikari/files.py
hikari/guilds.py
hikari/impl/cache.py
hikari/impl/entity_factory.py
hikari/impl/event_factory.py
hikari/impl/event_manager_base.py
hikari/impl/shard.py
hikari/impl/voice.py
hikari/internal/cache.py
hikari/internal/enums.py
tests/hikari/impl/test_entity_factory.py
tests/hikari/impl/test_shard.py
tests/hikari/internal/test_collections.py

- update_voice_state allows self_mute and self_deaf to be undefined.UNDEFINED
- PartialApplication.description and PartialApplication.summary now default to None
- Improve detecting mimetype in files.py
- Document DMPinsUpdateEvent as needing DM_MESSAGES intent

Fix some todos

---

hikari/users.py

(https://github.com/discord/discord-api-docs/issues/2494)

Remove the user system flag

---

hikari/applications.py

These seem to have been removed from the relevant pr to the api docs before merging by night for whatever reason: https://github.com/discord/discord-api-docs/pull/2624

Remove undocumented application flags

---

hikari/impl/entity_factory.py
hikari/internal/cache.py
hikari/presences.py
tests/hikari/impl/test_entity_factory.py

Add presence activity buttons
Closes #524

Add presence activity buttons

---

hikari/api/rest.py
hikari/impl/rest.py
tests/hikari/impl/test_rest.py

Update fetch welcome screen docs and behaviour

Update fetch welcome screen docs and behaviour

---

hikari/api/entity_factory.py
hikari/api/rest.py
hikari/channels.py
hikari/guilds.py
hikari/impl/bot.py
hikari/impl/entity_factory.py
hikari/impl/rest.py
hikari/internal/cache.py
hikari/internal/routes.py
hikari/permissions.py
hikari/snowflakes.py
hikari/traits.py
hikari/voices.py
tests/hikari/impl/test_bot.py
tests/hikari/impl/test_cache.py
tests/hikari/impl/test_entity_factory.py
tests/hikari/impl/test_rest.py

Add stage channels
Closes #527
Fixes #546

Add stage channels

---

.github/workflows/ci.yml
speedup-requirements.txt

- Remove python version limit on aiodns
Closes #537

Fix pipelines to install wheel and setuptools

---

.idea/fileTemplates/Python Module.py
docs/config.mako
hikari/colors.py
hikari/emojis.py
hikari/impl/rest.py
hikari/internal/deprecation.py
hikari/internal/fast_protocol.pyi
hikari/internal/ux.py
tests/hikari/internal/test_ux.py

https://www.python.org/dev/peps/pep-0632/

Move away from distutils as it has been deprecated

---

hikari/api/entity_factory.py
hikari/audit_logs.py
hikari/errors.py
hikari/impl/entity_factory.py
hikari/impl/event_factory.py
hikari/impl/event_manager_base.py
tests/hikari/impl/test_entity_factory.py
tests/hikari/test_audit_logs.py

Handle unknown entities

---

hikari/internal/routes.py
tests/hikari/internal/test_routes.py

Only account for specific major param combinations

---

dev-requirements.txt

Freeze pytest to fix CPython 3.10 issues

---

hikari/errors.py

Document new REST error codes

---

.github/workflows/ci.yml
pipelines/pytest.nox.py

Add flag to disable collecting coverage

---

hikari/guilds.py
hikari/impl/entity_factory.py
hikari/invites.py
tests/hikari/impl/test_entity_factory.py
tests/hikari/test_guilds.py

Add guild.is_nsfw field

---

hikari/impl/entity_factory.py
hikari/impl/rest.py
hikari/internal/cache.py
hikari/invites.py
tests/hikari/impl/test_entity_factory.py
tests/hikari/impl/test_rest.py
tests/hikari/test_invites.py

Add expires_at field to Invite object + invite refactors
* Fix max_uses not being set to None when it's 0

Add expires_at field to Invite object + invite refactors

---

hikari/embeds.py
hikari/internal/collections.py
hikari/internal/enums.py
hikari/internal/spel.py
tests/hikari/events/test_typing_events.py
tests/hikari/impl/test_shard.py
tests/hikari/internal/test_enums.py
tests/hikari/test_snowflake.py

On our way to 100% coverage

---

hikari/api/rest.py
hikari/impl/rest.py
hikari/messages.py
hikari/webhooks.py
tests/hikari/test_messages.py
tests/hikari/test_webhooks.py

Implement adding and replacing attachments in message PATCH

---

hikari/applications.py
hikari/audit_logs.py
hikari/channels.py
hikari/embeds.py
hikari/events/message_events.py
hikari/events/typing_events.py
hikari/guilds.py
hikari/impl/cache.py
hikari/internal/attr_extensions.py
hikari/internal/net.py
hikari/invites.py
hikari/snowflakes.py
hikari/users.py
hikari/webhooks.py

Make some imports type checking only

Make some imports type checking only

---

hikari/impl/event_manager_base.py

Handle InvalidStateError on waiter dispatch

Handle InvalidStateError on waiter dispatch

---

hikari/api/rest.py
hikari/api/special_endpoints.py
hikari/impl/rest.py
hikari/impl/special_endpoints.py
tests/hikari/impl/test_rest.py

Add  stage channel methods for RESTClient and GuildBuilder

Add stage channel methods 

---

hikari/impl/bot.py
hikari/impl/event_factory.py
hikari/impl/special_endpoints.py
tests/hikari/impl/test_bot.py
tests/hikari/test_errors.py

Add tests for BotApp

---

hikari/__init__.py
hikari/errors.py
hikari/impl/event_factory.py

Document new REST error codes and remove unnecessary ones

---

hikari/applications.py
hikari/impl/entity_factory.py
hikari/impl/special_endpoints.py
hikari/iterators.py
tests/hikari/impl/test_entity_factory.py
tests/hikari/test_applications.py

Implement Team#name

---

hikari/api/event_factory.py
hikari/events/shard_events.py
hikari/impl/event_factory.py
hikari/impl/event_manager_base.py
tests/hikari/impl/test_event_factory.py
tests/hikari/impl/test_event_manager_base.py

Add shard event payload dispatch

Add shard event payload dispatch

---

hikari/impl/bot.py

Reset closing event on bot start

---

hikari/users.py

https://github.com/discord/discord-api-docs/pull/2946

Document DISCORD_CERTIFIED_MODERATOR

---

hikari/impl/rest.py

Allow to not specify permissions in `create_role`

---

hikari/guilds.py
tests/hikari/test_guilds.py

Move helpful guild properties to the Guild object

---

hikari/channels.py
hikari/guilds.py
tests/hikari/test_channels.py
tests/hikari/test_guilds.py

Add mention properties to GuildChannel and PartialRole

Add mention properties to GuildChannel and PartialRole

---

hikari/errors.py

Document new 20031 error code

---

hikari/api/event_factory.py
hikari/events/shard_events.py
hikari/impl/event_factory.py

Rename ShardPayload to ShardPayloadEvent

Rename ShardPayload to ShardPayloadEvent

---

hikari/impl/shard.py

Replace json.* with data_binding.json_* where appropriate

---

hikari/intents.py
hikari/permissions.py
tests/hikari/test_permissions.py

Add thread permissions + all perms method
* Add note for permissions which can be gated behind 2fa

Add thread permissions + all perms method

---

hikari/emojis.py
hikari/events/base_events.py
hikari/events/channel_events.py
hikari/events/guild_events.py
hikari/events/member_events.py
hikari/events/message_events.py
hikari/events/reaction_events.py
hikari/events/role_events.py
hikari/events/shard_events.py
hikari/events/typing_events.py
hikari/events/voice_events.py
hikari/impl/event_factory.py
hikari/internal/collections.py

Add in missing slots + avoid using attrs to define the slots for pure ABCs

Add in missing slots + avoid using attrs to define the slots for pure ABCs

---

README.md

Update uvloop section to include UNIX systems

---

hikari/api/rest.py
hikari/channels.py
hikari/messages.py
hikari/users.py
hikari/webhooks.py

Remove incorrect documentation of 400 caused by allowed mentions

Remove incorrect documentation of 400 caused by allowed mentions

---

hikari/impl/bot.py
hikari/impl/event_manager_base.py
hikari/internal/aio.py
tests/hikari/__init__.py
tests/hikari/impl/test_bot.py
tests/hikari/impl/test_shard.py
tests/hikari/internal/test_aio.py

Improve loop acquisition in BotApp.run
Fixes: #626

Improve loop acquisition in BotApp.run

---

hikari/impl/rest.py

Do not send "embeds" in message create payloads when not specified

---

hikari/files.py
hikari/internal/aio.py
hikari/internal/attr_extensions.py
hikari/iterators.py

Remove unnecessary typing casts

---

hikari/errors.py

Add new rest error codes

---

hikari/guilds.py

Document new guild features

---

hikari/impl/entity_factory.py
tests/hikari/impl/test_entity_factory.py

Default content to None when empty string

---

.github/workflows/ci.yml

Add ci-done job

---

hikari/api/rest.py
hikari/channels.py
hikari/impl/rest.py
tests/hikari/test_channels.py

This pr adds the methods specified #35
#35

Add channel methods

---

hikari/events/guild_events.py

Add artificial user_id property to BanCreateEvent 

---

hikari/impl/special_endpoints.py

Account for entries being ignored in audit log iter

Account for entries being ignored in audit log iter

---

hikari/api/rest.py
hikari/applications.py
hikari/impl/entity_factory.py
hikari/impl/rest.py
hikari/internal/cache.py
hikari/invites.py
tests/hikari/impl/test_cache.py
tests/hikari/impl/test_entity_factory.py
tests/hikari/impl/test_rest.py

Implement `target_application` and rename `target_user_type` to `target_type`

---

hikari/files.py

Fix Resourceish union by filling Resource generic value

Fix Resourceish union by filling Resource generic value

---

CONTRIBUTING.md
README.md
hikari/emojis.py
pipelines/twemoji.nox.py
scripts/test_twemoji_mapping.py

Account for more cases of not removing 0xfe0f in emoji.filename

Account for more cases of not removing 0xfe0f in emoji.filename

---

hikari/impl/rest_bot.py
tests/hikari/impl/test_rest_bot.py

Actually start rest client in rest bot

Actually start rest client in rest bot

---

examples/image_resources/image_resources.py

Use the walrus OP because it saves you from doing guild.icon_url twice and it's also more consistent as the OP is used above. Also to use brackets/parentheses in the first usage of the OP as recommended by python.

Use walrus OP in examples

---

dev-requirements.txt

Bump coverage to 6.0b1 to fix safety issue

Bump coverage to 6.0b1

---

README.md

Update the bot constructor example in `README.md` to `hikari.GatewayBot` since `hikari.BotApp` will/is deprecated.

Update README.md BotApp example to GatewayBot.

---

hikari/impl/special_endpoints.py
tests/hikari/impl/test_special_endpoints.py

Account for embed attachments in InteractionMessageBuilder.build

Account for embed attachments in InteractionMessageBuilder.build

---

hikari/interactions/commands.py

Support the Number application command option type

Support the Number application command option type

---

hikari/interactions/commands.py
hikari/messages.py

Remove shadowing which was leading to unknown types in pyright

Remove shadowing which was leading to unknown types in pyright

---

hikari/api/voice.py
hikari/impl/voice.py
tests/hikari/impl/test_voice.py

- Allow disconnecting from voice channel
- ~~Allow moving voice channel in the same server~~
Closes #693

Fix some bugs in voice impl

---

hikari/impl/voice.py
tests/hikari/impl/test_voice.py

Add missing _check_if_alive to VoiceComponent

---

hikari/internal/aio.py
tests/hikari/impl/test_rest_bot.py
tests/hikari/internal/test_aio.py

Fix DeprecationWarnings on python 3.10

---

hikari/internal/time.py
pipelines/mypy.nox.py

Install speedups in mypy pipeline to load stubs for them

---

hikari/errors.py
tests/hikari/test_errors.py

- Improve HTTPResponseError to make use of the code if available

Document new REST Codes

---

.github/workflows/ci.yml
CONTRIBUTING.md
README.md
dev-requirements.txt
hikari/api/cache.py
hikari/api/rest.py
hikari/api/special_endpoints.py
hikari/colors.py
hikari/errors.py
hikari/events/guild_events.py
hikari/guilds.py
hikari/impl/rest.py
hikari/impl/shard.py
hikari/internal/cache.py
hikari/internal/enums.py
hikari/internal/spel.py
hikari/internal/time.py
hikari/iterators.py
pipelines/codespell.nox.py
pipelines/format.nox.py
tests/hikari/impl/test_shard.py
tests/hikari/test_undefined.py
tests/hikari/test_webhooks.py

Add codespell pipeline to CI

---

README.md

Add tanjun to the readme.md

---

hikari/config.py
hikari/impl/cache.py
tests/hikari/impl/test_cache.py

Fix dm_channel_id cache component check

---

hikari/api/entity_factory.py
hikari/api/rest.py
hikari/api/special_endpoints.py
hikari/commands.py
hikari/events/interaction_events.py
hikari/impl/entity_factory.py
hikari/impl/rest.py
hikari/impl/special_endpoints.py
hikari/internal/routes.py
tests/hikari/impl/test_entity_factory.py
tests/hikari/impl/test_rest.py
tests/hikari/impl/test_special_endpoints.py
tests/hikari/test_commands.py

Implement Slash Command Permissions
~~This is blocked by #701~~

Implement Slash Command Permissions

---

hikari/__init__.py
hikari/__init__.pyi
hikari/api/entity_factory.py
hikari/api/rest.py
hikari/emojis.py
hikari/impl/entity_factory.py
hikari/impl/rest.py
hikari/internal/cache.py
hikari/internal/routes.py
hikari/messages.py
hikari/permissions.py
hikari/stickers.py
hikari/webhooks.py
tests/hikari/impl/test_cache.py
tests/hikari/impl/test_entity_factory.py
tests/hikari/impl/test_rest.py

Implement new sticker models + routes

---

hikari/audit_logs.py

This pr adds the audit log events related to stickers.

add sticker events to audit log types

---

hikari/channels.py

Removes the excess documentation for fetch_guild.

fix fetch_guild's documentation

---

CHANGELOG.md
hikari/applications.py
tests/hikari/test_applications.py

Added application methods.
#33

Adding application methods

---

.github/workflows/ci.yml

Re-enable 3.10 test workflows

---

hikari/api/rest.py
hikari/config.py

Thanks to @ZeusAbhijeet and @ben2224 for pointing them out to me

Fix spelling mistakes in documentation

---

hikari/permissions.py
tests/hikari/test_permissions.py

Add USE_EXTERNAL_STICKERS perm

---

hikari/messages.py

Add new message type + rename application command

---

hikari/commands.py
hikari/impl/entity_factory.py
tests/hikari/impl/test_entity_factory.py
tests/hikari/test_commands.py

Add ApplicationCommand.version

---

CONTRIBUTING.md
changes/778.removal.md
hikari/__init__.py
hikari/__init__.pyi
hikari/impl/bot.py
hikari/traits.py
tests/hikari/test_presences.py

Remove deprecated `BotApp`

---

changes/785.bugfix.md
hikari/impl/entity_factory.py
hikari/interactions/command_interactions.py
tests/hikari/impl/test_entity_factory.py

Cast `CommandOption.value` to a `Snowflake` for types 6-9

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/fragments-check.yml
.github/workflows/prepare-release.yml
coverage.ini
hikari/api/rest.py
hikari/impl/entity_factory.py
hikari/impl/rest.py
hikari/impl/voice.py
hikari/internal/data_binding.py
hikari/internal/routes.py
tests/hikari/events/test_reaction_events.py
tests/hikari/impl/test_bot.py
tests/hikari/impl/test_entity_factory.py
tests/hikari/impl/test_interaction_server.py
tests/hikari/impl/test_rest.py
tests/hikari/impl/test_rest_bot.py
tests/hikari/impl/test_voice.py
tests/hikari/internal/test_data_binding.py
tests/hikari/test_channels.py
tests/hikari/test_guilds.py
tests/hikari/test_stickers.py
tests/hikari/test_webhooks.py

Add tests for some more modules

---

CHANGELOG.md
CONTRIBUTING.md
hikari/api/special_endpoints.py
hikari/messages.py

Small doc fixes around menu value ranges

---

.github/workflows/ci.yml
.github/workflows/release.yml
pipelines/format.nox.py

Move release CI to separate file

---

hikari/messages.py

Fix how remove_reaction's example targeted users

Fix how remove_reaction's example targeted users

---

changes/816.breaking.md
hikari/errors.py
hikari/internal/net.py
tests/hikari/test_errors.py

Remove RESTErrorCode enum

---

changes/820.breaking.md
hikari/channels.py
hikari/impl/rest.py
hikari/interactions/base_interactions.py
hikari/interactions/command_interactions.py
hikari/interactions/component_interactions.py

Remove Unique pattern and hashing from Overwrites

Remove Unique pattern and hashing from Overwrites

---

changes/809.breaking.md
changes/809.feature.md
hikari/api/event_factory.py
hikari/events/guild_events.py
hikari/impl/event_factory.py
hikari/impl/event_manager.py
tests/hikari/impl/test_event_factory.py
tests/hikari/impl/test_event_manager.py

Separate the guild join event from the guild available event since apparently, new guilds won't have the `unavailable` field present.

Implement GuildJoinEvent

---

hikari/channels.py

Add `allow` and `deny` to PermissionOverwrite's repr

---

changes/817.bugfix.md
hikari/impl/rest.py

Funnily enough, this also speeds it up a bit :P

Fix BulkDeleteError showing incorrect values

---

changes/897.breaking.md
changes/897.feature.md
hikari/api/event_factory.py
hikari/events/message_events.py
hikari/impl/event_factory.py
hikari/impl/event_manager.py
tests/hikari/events/test_message_events.py
tests/hikari/impl/test_event_factory.py
tests/hikari/impl/test_event_manager.py

Split bulk message delete and message delete into separate events

---

.github/workflows/ci.yml
.github/workflows/prepare-release.yml
scripts/deploy.sh
scripts/prepare-release.sh

- Fix skip ci message
- Enable auto-merge for the pre-release pull requests
- Escape markdown for pr_body

Fix release workflow

---

.github/dependabot.yml

No real need to both assign and request a review. We can leave assignment when something needs to be done to the PR

Dont assign dependabot pull requests

---

changes/939.feature.md
hikari/applications.py
hikari/impl/entity_factory.py
tests/hikari/impl/test_entity_factory.py

https://github.com/discord/discord-api-docs/commit/99d5ae215900df91c0baf9e44c428e54718152de

Add flags to Application

---

changes/960.feature.md
changes/idk.feature.md
hikari/presences.py

Add new presence activity flags.

---

changes/957.feature.md
changes/idk.feature.md
hikari/guilds.py

Add the SUPPRESS_USER_JOIN_REPLIES system channel flag

Add the SUPPRESS_USER_JOIN_REPLIES system channel flag

---

changes/959.feature.md
changes/idk.feature.md
hikari/users.py

Add the BOT_HTTP_INTERACTIONS user flag

---

changes/958.feature.md
changes/ikd.feature.md
hikari/applications.py

Add new message content related application flags

---

pyproject.toml

Enable pytest-asyncio strict mode

---

MANIFEST.in

Remove requirements files from the manifest

---

pipelines/pytest.nox.py
pyproject.toml

Fix coverage collection

---

changes/1015.feature.md
changes/idk.feature.md
hikari/commands.py
hikari/impl/entity_factory.py
hikari/interactions/command_interactions.py
tests/hikari/impl/test_entity_factory.py

Add attachment command option type support

---

scripts/deploy.sh
scripts/prepare-release.sh

After this I am not going to do any changes to the deploy script ever again. I thought I had tested every line thoroughly and nothing was wrong. Turns out I forgot to escape a the `$` character, so no errors were being raised. Additionally I thought I copy pasted each line to avoid any issues, looks like I didnt.
After this I will just create a small release and yank `2.0.0.dev106`. Not much has changed since.
I am deeply sorry

Fix deploy for the last time ever

---

hikari/internal/data_binding.py

Rename covariant `T` to `T_co`.

---

.github/workflows/ci.yml
.github/workflows/prepare-release.yml
CHANGELOG.md
docs/config.mako
hikari/api/interaction_server.py
hikari/api/rest.py
hikari/guilds.py
hikari/impl/bot.py
hikari/impl/event_manager_base.py
hikari/impl/interaction_server.py
hikari/impl/rate_limits.py
hikari/impl/rest_bot.py
hikari/internal/enums.py
hikari/internal/time.py
hikari/presences.py
hikari/snowflakes.py
tests/hikari/impl/test_buckets.py
tests/hikari/test_guilds.py

Fix various spelling mistakes across 15 files.
This is a work in progress I haven't checked *everything* yet!
And for those wondering why I'm still coding instead of focusing on school, I'm on holiday! :<
* verify-types failed, something to do with the environment already existing 🤷‍♂️

Fix various spelling mistakes

---

hikari/api/rest.py
hikari/audit_logs.py
hikari/impl/bot.py

Some small doc fixes

---

changes/1041.feature.md
hikari/impl/shard.py

Change failed to communicate with server log to a warning

---

changes/1024.doc.md
examples/slash.py

Added a slash command example since Hikari was lacking one.

Add a slash command example

---

changes/841.bugfix.md
hikari/impl/buckets.py
hikari/impl/rate_limits.py
hikari/impl/rest.py
tests/hikari/impl/test_buckets.py
tests/hikari/impl/test_rate_limits.py

Fix bucket lock not being released on errors while being acquired

---

changes/1041.feature.md

Changelog typo fix

---

changes/1058.feature.md
hikari/impl/shard.py
tests/hikari/impl/test_shard.py

Optimize 'receive_json' for the happy path

---

changes/1065.bugfix.md
changes/bugfix.idk.md
hikari/events/channel_events.py
hikari/events/interaction_events.py
hikari/events/member_events.py
hikari/events/role_events.py
hikari/events/typing_events.py
hikari/events/voice_events.py

Add missing event to channel_events.__all__

Add missing event to channel_events.__all__

---

hikari/impl/entity_factory.py

Remove set_guild_attributes

---

hikari/impl/entity_factory.py
hikari/interactions/command_interactions.py
hikari/users.py
tests/hikari/impl/test_entity_factory.py

Fix some bugs and a regression introduced by https://github.com/hikari-py/hikari/pull/1090.

Fix locale bugs and regressions

---

hikari/impl/event_factory.py

Remove redundant event factory assertions

---

hikari/__init__.py
hikari/__init__.pyi

Remove functions exported in top level package

---

dev-requirements.txt
hikari/permissions.py

Fix the errors in the examples, and make the explanations more clear and concise
Closes #1133

Fix docs examples for hikari.Permissions

---

hikari/snowflakes.py
tests/hikari/test_snowflake.py

Simplify logic for snowflake min and max

---

changes/1144.bugfix.md
hikari/locales.py

Fix typo. I also checked the others and they're now all correct.
Whoops.

fix: locale polish

---

hikari/api/config.py

Add data classes to `hikari.api.config.__all__`

---

hikari/impl/shard.py
tests/hikari/impl/test_shard.py

https://github.com/discord/discord-api-docs/commit/6755c355caaf2e1c321dc7de17e1e257d9aa2db5

Remove dollar sign from identify payload

---

.github/workflows/ci.yml

Improve ci-done workflow

---

changes/1126.feature.md
hikari/api/cache.py
hikari/api/config.py
hikari/api/entity_factory.py
hikari/api/event_factory.py
hikari/events/guild_events.py
hikari/guilds.py
hikari/impl/cache.py
hikari/impl/entity_factory.py
hikari/impl/event_factory.py
hikari/impl/event_manager.py
hikari/internal/cache.py
tests/hikari/events/test_guild_events.py
tests/hikari/impl/test_cache.py
tests/hikari/impl/test_entity_factory.py
tests/hikari/impl/test_event_factory.py
tests/hikari/impl/test_event_manager.py
tests/hikari/internal/test_cache.py
tests/hikari/test_guilds.py

Adds `StickersUpdateEvent` and the associated cache internals.
Adds public cache methods onto `Guild` and `impl.CacheImpl`.
Let me know if I missed anything.
Closes #1122 
Closes #866

Add StickersUpdateEvent

---

changes/1225.feature.md
hikari/applications.py
tests/hikari/internal/test_cache.py

Add the new application commands badge to `ApplicationFlags`.

Add application commands badge

---

changes/1243.bugfix.md
hikari/impl/entity_factory.py
tests/hikari/impl/test_entity_factory.py

dm_permission defaults to True not False

---

.github/dependabot.yml

Remove redundant dependabot target

---

hikari/__init__.py
hikari/__init__.pyi

Expose __git_sha1__ (and other fields) top level

---

hikari/impl/special_endpoints.py
tests/hikari/impl/test_special_endpoints.py

Include name_localizations on MenuBuilder.create

---

hikari/commands.py

Call a context menu command a context menu command not a slash command.

---

changes/1284.bugfix.md
hikari/impl/event_manager.py
tests/hikari/impl/test_event_manager.py

Ignore GUILD_CREATE which contain unavailable guilds

---

changes/1213.bugfix.md
hikari/errors.py
tests/hikari/test_errors.py

Improve BadRequestError error string

---

dev-requirements/flake8.txt
hikari/api/rest.py
hikari/guilds.py
hikari/impl/rest.py
hikari/internal/deprecation.py
hikari/messages.py
pipelines/config.py
pyproject.toml
tests/hikari/__init__.py
tests/hikari/events/test_guild_events.py
tests/hikari/impl/test_rest.py
tests/hikari/internal/test_deprecation.py
tests/hikari/test_guilds.py

Turn warnings into errors in tests

---

changes/1245.feature.md
hikari/events/shard_events.py
hikari/impl/event_factory.py
hikari/impl/shard.py
tests/hikari/events/test_shard_events.py
tests/hikari/impl/test_event_factory.py
tests/hikari/impl/test_shard.py

New gateway resume logic

---

changes/1204.breaking.md
changes/1204.feature.md
scripts/prepare-release.sh

Fix towncrier installation

---

hikari/impl/shard.py
tests/hikari/impl/test_shard.py

Allow to change shard trace level on the fly

---

hikari/api/rest.py
hikari/api/special_endpoints.py

Fix docstrings

---

hikari/impl/.gitattributes

Add .gitattributes file

---

README.md
hikari/api/shard.py
hikari/impl/rest.py
hikari/impl/shard.py

chore: update Discord API version in README

---

.github/workflows/ci.yml

Just to improve actions logs readability

Split linting commands

---

README.md

Fix readme ver list

---

hikari/impl/__init__.py
hikari/impl/__init__.pyi
hikari/impl/shard.py

Expose shard impl

---

dev-requirements/flake8.txt
hikari/api/cache.py
hikari/api/interaction_server.py
hikari/api/rest.py
hikari/api/special_endpoints.py
hikari/channels.py
hikari/colors.py
hikari/impl/entity_factory.py
hikari/impl/rate_limits.py
hikari/impl/special_endpoints.py
hikari/internal/aio.py
hikari/internal/data_binding.py
hikari/users.py
hikari/webhooks.py
tests/hikari/impl/test_rest.py
tests/hikari/internal/test_signals.py

Add plugin to verify noqa comments

---

hikari/impl/shard.py

Fix error in logs due to missing replacement variable

---

hikari/api/cache.py
hikari/api/rest.py
hikari/api/special_endpoints.py
hikari/files.py
hikari/interactions/base_interactions.py
hikari/interactions/modal_interactions.py
hikari/internal/cache.py

Remove left-over `builtins.` from docs

---

hikari/interactions/base_interactions.py

Signed-off-by: thomm.o <43570299+tandemdude@users.noreply.github.com>

Fix grammar

---

changes/1404.feature.md
hikari/locales.py

https://github.com/discord/discord-api-docs/pull/5643

locale: add indonesian

---

changes/1435.bugfix.md
hikari/impl/rest.py
tests/hikari/impl/test_rest.py

Actually start bucket manager gc

---

docs/_static/extra.css
docs/conf.py
hikari/impl/bot.py
hikari/users.py

Adds this for visual aid
Also, make them sort groupwise

Improve the docs TOC

---

changes/1431.feature.md
hikari/impl/bot.py
hikari/impl/rest_bot.py
hikari/internal/ux.py
tests/hikari/impl/test_bot.py
tests/hikari/impl/test_rest_bot.py
tests/hikari/internal/test_ux.py

Add a warning when not running in optimized mode

---

hikari/guilds.py
hikari/impl/rest.py

Due to the hotfix, I think its only fair to leave some more time.

Bump features marked for deletion in 2.0.0.dev116 to 2.0.0.dev117

---

hikari/internal/deprecation.py
hikari/internal/enums.py
hikari/internal/enums.pyi
tests/hikari/internal/test_enums.py

Add utilities to aid with enum member deprecation

---

changes/1480.bugfix.md
hikari/impl/entity_factory.py
hikari/webhooks.py
tests/hikari/impl/test_entity_factory.py

Fix `ChannelFollowWebhook` not including source in all cases

---

changes/1485.breaking.md
changes/1485.bugfix.md
changes/1485.feature.md
hikari/impl/bot.py
hikari/impl/rest_bot.py
hikari/internal/ux.py
tests/hikari/internal/test_ux.py

Improve logging consistency and add support for `.ini` files

---

hikari/impl/rest.py
hikari/internal/data_binding.py
tests/hikari/impl/test_rest.py
tests/hikari/internal/test_data_binding.py

Fix `URLEncodedFormBuilder` treating fields as files

---

hikari/api/rest.py
hikari/templates.py

Remove newer references to RateLimitedError

---

changes/1508.feature.md
hikari/impl/special_endpoints.py

Export other select menu builder types properly

---

changes/1529.bugfix.md
hikari/impl/buckets.py
hikari/impl/rest.py
tests/hikari/impl/test_buckets.py
tests/hikari/impl/test_rest.py

Await bucket manager gc task to completion when closing

---

changes/1560.bugfix.md
changes/idk.bugfix.md
hikari/impl/special_endpoints.py

Add in missed field aliases for imessagebuilder mention fields

---

hikari/api/rest.py
hikari/impl/rest.py
hikari/interactions/command_interactions.py
tests/hikari/interactions/test_command_interactions.py

Just a small follow up to #1539

Support Autocomplete response builder for interaction methods

---

hikari/internal/ux.py

This PR adjusts the wording on the level 0 optimization warning.
N/A

Update warning for optimization level 0

---

changes/1628.bugfix.md
hikari/impl/entity_factory.py

Properly handle DM channels in resolved interaction channels

---

hikari/impl/entity_factory.py

`_set_user_attrsibutes` -> `_set_user_attributes`

Fix function name typo

---

.github/workflows/fragments-check.yml

Test can be seen at https://github.com/davfsa/hikari/pull/23

Automatically rename changelog fragments that start with idk

---

changes/1720.bugfix.md
hikari/impl/entity_factory.py
tests/hikari/impl/test_entity_factory.py

Fix ["revoked"] KeyError for `deserialize_own_connection`

---

changes/1812.bugfix.md
hikari/guilds.py
hikari/impl/entity_factory.py
hikari/internal/cache.py
tests/hikari/impl/test_entity_factory.py

Discord making breaking changes :D
Closes #1811

`Member.joined_at` can now be None

---

changes/1933.feature.md
hikari/embeds.py

Add `clear_fields` method to `Embed` to remove all existing fields from the embed.

Add Embed.clear_fields() method

---

changes/1951.feature.md
hikari/users.py
tests/hikari/test_users.py

Add `display_name` to `PartialUser`

---

changes/2020.feature.md
hikari/api/rest.py
hikari/impl/rest.py
hikari/internal/routes.py
tests/hikari/impl/test_rest.py

[Added this](https://discord.com/developers/docs/change-log#get-guild-role-endpoint)

Add fetch_role function

---

changes/2100.documentation.md
hikari/api/shard.py
hikari/traits.py

Added missing Documenatation for GatewayShard and ShardTrait

Add missing shard error documentation

---

tests/hikari/internal/test_aio.py

Fix failing macOS test due to closed event loop

---

changes/2168.bugfix.md
hikari/impl/rest.py

Properly handle cloudflare bans

---

hikari/impl/entity_factory.py
tests/hikari/impl/test_entity_factory.py

Fix application command deserialization when context is None

---

.github/CODEOWNERS
.github/FUNDING.yml
README.md
SECURITY.md

- Remove FasterSpeeding from codeowners, funding and security file
- Cleanup README
- Add missing yuyo link
- Sort lists by order of addition instead of alphabetically

General housekeeping

---

hikari/api/rest.py

Fix the documentation for create_role. Also adjust the default value to reflect the impl.

Fix docs of create_role

---

index.html

Update the wording on the landing page to reflect the current state of the project. Also update the Discord invite link.

Update website landing page

---

hikari/interactions/base_interactions.py
hikari/messages.py
hikari/webhooks.py
tests/hikari/interactions/test_base_interactions.py
tests/hikari/test_webhooks.py

feat: support for poll parameter in utility methods

---

hikari/api/special_endpoints.py
hikari/impl/special_endpoints.py

feat: poll support for REST-based interaction responses

---

hikari/api/special_endpoints.py

docs: add unit for poll builder duration

---

changes/2196.feature.md

Doesnt exist yet, but will in the future :D

Add components v2 Discord documentation link

---

changes/2336.bugfix.md
changes/2336.optimization.md
hikari/impl/entity_factory.py
hikari/impl/rest.py
tests/hikari/impl/test_rest.py

Fix duplicated uploaded attachments when reusing resources in embeds

---

CONTRIBUTING.md
tests/hikari/impl/test_event_manager_base.py
tests/hikari/impl/test_rest.py
tests/hikari/impl/test_special_endpoints.py

Remove leftover mentions of flake8

---

changes/2398.feature.md
hikari/messages.py

feat(MessageFlag): add missing "HAS_THREAD" message flag.

---

changes/2469.feature.md
hikari/applications.py
hikari/guilds.py
hikari/impl/entity_factory.py
hikari/impl/event_factory.py
hikari/internal/routes.py
hikari/users.py
tests/hikari/impl/test_entity_factory.py
tests/hikari/integration/test_equality_comparisons.py
tests/hikari/test_users.py

Add support for the new user object `primary_guild` for the new discord tags feature.

Add primary guild support.

---

changes/2498.feature.md
changes/idk.feature.md
hikari/api/rest.py
hikari/channels.py
hikari/permissions.py
tests/hikari/test_permissions.py

Add `PIN_MESSAGE` permission

---

changes/2556.feature.md
hikari/impl/buckets.py
tests/hikari/__init__.py
tests/hikari/impl/test_buckets.py

feat: improve buckets ratelimiting logic
